### ISSUE TITLE
More Formats for Compact Currency

### ISSUE THREAD

**Issue by YousefEZ** [python-babel/babel#1004]
Can we have more format types for the format_compact_currency function, I was thinking ``spaced`` which would put a space between the number and the scale so like ``3 M`` rather than ``3M``, as well as ``long`` which would write it in word form i.e. ``billion``, ``million``, ``thousand`` etc?
https://github.com/python-babel/babel/blob/134c792df3b6aa84de3e74e81a875493c95dcc2e/babel/numbers.py#L718

**Comment by akx** [comment]
If those formats are specified in the CLDR, then yes. We wouldn't be able to support arbitrary formats for all languages supported by Babel otherwise...

**Comment by akx** [comment]
Closing as stale.
