### ISSUE TITLE
narrow non-breaking space (\u202f) usage in datetime formatting

### ISSUE THREAD

**Issue by joeyorlando** [python-babel/babel#1012]
## Overview Description

On version `2.12.1`, is it intended that "\u202f" would be included in an `en` localized datetime?

## Steps to Reproduce

```python3
>>> import babel
>>> import datetime
>>> now = datetime.datetime.now()
>>> babel.dates.format_datetime(now, format="short", locale="en")
'6/13/23, 3:27\u202fPM'
```

**Comment by joeyorlando** [comment]
seems _somewhat_ related to #1007 ?

**Comment by akx** [comment]
That formatting comes from the Unicode CLDR data, and Babel itself doesn't have an opinion.

The intention with an NBSP is that the AM/PM marker doesn't wrap onto a second line where it could, e.g. in

```
6/13/23, 3:27
PM
```
but remains attached to the time instead, and the user agent would wrap elsewhere:
```
6/13/23,
3:27 PM
```

The narrowness is likely a typographic choice.

I'll close this off, but let me know if you have further questions!
