### ISSUE TITLE
Support for additional common date formats

### ISSUE THREAD

**Issue by jonocodes** [python-babel/babel#1018]
## Overview Description

As an example there should be a way to produce a month/day formatted date in accordance with locale.

en = October 12
de = 12. Oktober

Django handles this using additional localized formatters:
https://github.com/django/django/blob/main/django/conf/locale/de/formats.py

In this case it would be using the MONTH_DAY_FORMAT, but the other ones would be good as well.

And here is how shuup does it:
https://github.com/shuup/shuup/blob/25f78cfe370109b9885b903e503faac295c7b7f2/shuup/utils/dates.py#L41

It supports fewer formats, but does mention following CLDR.

**Comment by akx** [comment]
Heh, I think I wrote that bit in Shuup. 😁 

Anyway, have you tried [`format_skeleton`](https://babel.pocoo.org/en/latest/api/dates.html#babel.dates.format_skeleton) with the [`MMMd` skeleton](https://cldr.unicode.org/translation/date-time/date-time-patterns#h.8495ml1t095x)? Does it do what you wnat?

**Comment by jonocodes** [comment]
Ah yes, that does what I need. Thanks!
