### ISSUE TITLE
Please add jalali date for persian local! 

### ISSUE THREAD

**Issue by mrr-r** [python-babel/babel#1020]
Hello dear
We use your great module but it has one big bug for persian language.
Please add jalali date for our locale date.
We can help you to resolve it.
Thank you!

**Comment by akx** [comment]
Implementing a new calendar system will be a pretty big undertaking for both initial development and ongoing support. I'm not sure there's bandwidth in this project for that.

**Comment by akx** [comment]
Closing as stale + duplicate of #810.
