### ISSUE TITLE
`pybabel extract` not working with constant inner f-strings

### ISSUE THREAD

**Issue by l1onsun** [python-babel/babel#1060]
## Steps to Reproduce
```python
# main.py
f"some string to {_('translate')}"
```
```bash
pybabel extract -o locales/messages.pot
```
(pybabel 2.14.0)

## Actual Results
No strings extracted

## Expected Results
extracted `'translate'` string

**Comment by tomasr8** [comment]
Looks like a duplicate of #1001 
Also, this works as expected in the latest babel version
