### ISSUE TITLE
Missing license for babel/locale-data

### ISSUE THREAD

**Issue by stefan6419846** [python-babel/babel#1072]
## Overview Description

`babel/locale-data` does not provide any license information, although being based on some third-party code.

## Steps to Reproduce

1. Download a *Babel* distribution.
2. Search for the Unicode license inside the package.

## Actual Results

There is no Unicode-related copyright information inside the distributions.

## Expected Results

The obligations of the Unicode/CLDR license terms are met inside the *Babel* distributions.

## Additional Information

Digging through the code of the repository, it turns out that `babel/locale-data` contains *pickle*-based custom representations of files downloaded from https://github.com/python-babel/babel/blob/fe82fbc90d8044d17bfc4ae1c7a0cb24e85153ef/scripts/download_import_cldr.py#L12 The corresponding ZIP file and repository (https://github.com/unicode-org/cldr) state in their `LICENSE.txt` (bold text/highlighting by me):

> Permission is hereby granted, free of charge, to any person obtaining a copy of data files and any associated documentation (the "Data Files") or software and any associated documentation (the "Software") to deal in the Data Files or Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, and/or sell copies of the Data Files or Software, and to permit persons to whom the Data Files or Software are furnished to do so, provided that **either (a) this copyright and permission notice appear with all copies of the Data Files or Software, or (b) this copyright and permission notice appear in associated Documentation.**

At the moment, there corresponding notice seems to be missing from *Babel* distributions and from the whole GitHub repository.

**Comment by akx** [comment]
Thank you, good point! Please see #1074 and feel free to review-approve it if you believe it fixes this.
