### ISSUE TITLE
Outdated docs for time zones

### ISSUE THREAD

**Issue by mj1856** [python-babel/babel#108]
The docs [here](http://babel.pocoo.org/docs/dates/) show the sample:

```python
>>> from babel import Locale
>>> from babel.dates import get_timezone_name, get_timezone

>>> tz = get_timezone('Europe/Berlin')
>>> get_timezone_name(tz, locale=Locale.parse('pt_PT'))
u'Hor\xe1rio Alemanha'
```
But the current code returns `"hora da Europa Central"`.  I assume that's because you're now resolving the time zone to the metazone and giving the translation for the metazone name.  That's fine, but the docs need to be updated.  Thanks.

**Comment by sils1297** [comment]
Hi, @mj1856 we're currently short of manpower, just taking over this repository. We would love a PR for this. Apart from that I'm marking this as `easy` and `ready to work upon`,  thanks for submitting the bug!

**Comment by etanol** [comment]
If you are using `master` it is probably caused by the update from CLDR 23.1 to CLDR 26
