### ISSUE TITLE
Full date format has changed for en_GB

### ISSUE THREAD

**Issue by jma** [python-babel/babel#1081]
## Overview Description

Since version 2.15.0, the comma disappears from the full date format for the British locale.

## Steps to Reproduce

Run the following code on version 2.14.0

```python
from datetime import datetime
from babel.dates import format_date
format_date(datetime(2024, 5, 6), 'full', locale='en_GB')
```
gives `'Monday, 6 May 2024'`.

Using the version 1.15.0,
it gives `'Monday 6 May 2024'`.

The "comma" is missing.

**Comment by akx** [comment]
Closing since there's nothing we can do about this on the Babel side of the fence.
