### ISSUE TITLE
format_datetime returns wrong date format for Panama

### ISSUE THREAD

**Issue by chronossc** [python-babel/babel#111]
Glibc and Wikipedia tell me that Panama has DD/MM/YYYY date format while babel returns dates in MM/DD/YYYY. This can be reproduced all times.

**Comment by akx** [comment]
Hey hey hey @chronossc!

You're correct -- this is definitely what's happening with Babel at present. However, the problem isn't directly Babel's, but the Unicode CLDR repository we draw our data from is at fault here (see the "CLDR reference" link in the list below). I googled around a little to find other reference links too. Some sources would indicate DD/MM/YY is the correct format for es_PA, but others indicate MM/DD/YY.

Unfortunately (unless we start maintaining some sort of "patch overlay" on top of the CLDR data we process, but that's another discussion) there isn't much we can do. If you care about this and would like to see the problem fixed, [please see the CLDR's change request instructions](http://cldr.unicode.org/index/bug-reports). Thanks (and sorry I couldn't be of more help here!).

## References

* [Glibc reference](https://github.com/lattera/glibc/blob/a2f34833b1042d5d8eeb263b4cf4caaea138c4ad/localedata/locales/es_PA#L115) - '%d/%m/%y'
* [CLDR reference](http://unicode.org/cldr/trac/browser/trunk/common/main/es_PA.xml#L152) - "MM/dd/yy"
* [Microsoft NLSWeb](https://www.microsoft.com/resources/msdn/goglobal/default.mspx?submitted=180A&OS=Windows%20Vista) - "MM/dd/yyyy"
* [Web reference (Panamanian newspaper)](http://www.panamaamerica.com.pa/economia/crisis-en-zlc-y-construccion-afecta-los-seguros-en-2015-1006074) - "23/12/15 - 12:00 AM"
* [Web reference (Panamanian ministry))](http://mire.gob.pa/) - "Martes, 22 de Diciembre de 2015" (no example of short format I could see)

**Comment by jtwang** [comment]
@akx - Actually, can we talk about "patch overlay"? We implemented an overlay system in our fork of babel and, if this is something that would be useful to other people, we'd be super happy to have it live in 'real' babel. :)

This seems possibly related, but maybe only vaguely so to #30 .

**Comment by akx** [comment]
@jtwang Sure, we can talk. :D Maybe open up a new issue for discussion and tell us what your fork has?

**Comment by jtwang** [comment]
Opened :) https://github.com/python-babel/babel/issues/344

**Comment by akx** [comment]
Note to self: see whether the current CLDR still has this problem.

**Comment by akx** [comment]
This has been fixed.

```
>>> from babel.dates import format_date
>>> format_date(datetime.date.today(), locale='es_PA')
'07/20/2018'
```
