### ISSUE TITLE
"unknown locale 'ie'" (Occidental/Interlingue)

### ISSUE THREAD

**Issue by buhtz** [python-babel/babel#1114]
It seems that babel do not support Occidental/Interlingue.

```
>>> import babel
>>> babel.Locale.parse('ie')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/babel/core.py", line 330, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'ie'
```

I am just an upstream maintainer need to deal with over 40 languages and having some helper scripts. One of that scripts now fails because of that new added language. Currently I can add some exceptional handling for that. But I would prefer to have it supported by babel.

Just for fun I also tried `"tlh"` language code for Klingon. It is also not supported.

Both of them are "official" standardized languages, with scientific interest and rare use in real live. I don't want to argue about the relevance of such languages. I don't care. But my users are. IMHO if there is an ISO language code I would say babel and similar packages should support it.

**Comment by buhtz** [comment]
Learned from other of your issues this might be because babel does stick to "CLDR" (not knowing what this is). If this is the case then you minimally should improve your error message to make it clear to the users that it is not "the fault" of babel but CLDR. This would prevent more distracting tickets in your project.

**Comment by akx** [comment]
See #689, #454, #344.

As it is, `Locale.parse()` only supports locales that have data in the [Unicode Common Locale Data Repository (the CLDR)](https://cldr.unicode.org/).

**Comment by buhtz** [comment]
It seems that "ie" is supported by CLDR (latest stable release 45). But I might be wrong or in the wrong version of CLDR?

https://www.unicode.org/cldr/charts/45/summary/ie.html

**Comment by akx** [comment]
Ah, good catch. #1077 – the PR to support CLDR 45 – has been merged but not released yet. I'm planning on getting around to releasing [Babel 2.16](https://github.com/python-babel/babel/milestone/11) soon.

**Comment by akx** [comment]
I can confirm `ie` is supported in my local working copy, so it'll be supported in 2.16:

```python
>>> import babel
>>> babel.Locale.parse('ie').territories["US"]
'Unit States'
```

**Comment by buhtz** [comment]
Thank you very much from the bit-team/backintime project.

**Comment by buhtz** [comment]
My apologize. It seems that "ie" is supported since your 2.15 release.

**Comment by akx** [comment]
No worries, thank you for the documentation PR! Closing this for the time being.
