### ISSUE TITLE
supporting a new locale?

### ISSUE THREAD

**Issue by abdelouahabb** [python-babel/babel#121]
can i get the support of `kab_DZ` because algeria does support other language than `arabic`
http://www.localeplanet.com/icu/kab-DZ/index.html

**Comment by etanol** [comment]
This is a CLDR specific issue.  The `kab_DZ.xml` source file from CLDR version 28 contains the following:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ldml SYSTEM "../../common/dtd/ldml.dtd">
<!-- Copyright © 1991-2015 Unicode, Inc.
CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
For terms of use, see http://www.unicode.org/copyright.html
-->
<ldml>
	<identity>
		<version number="$Revision: 11914 $"/>
		<language type="kab"/>
		<territory type="DZ"/>
	</identity>
</ldml>
```

Which means there are no specific definitions for such combinations.  Please submit a bug [directly to CLDR](http://cldr.unicode.org/index/bug-reports)
