### ISSUE TITLE
Keywords containing dots never match in JS

### ISSUE THREAD

**Issue by ThiefMaster** [python-babel/babel#148]
In our project we use `$t.gettext` in JavaScript files. However, `--no-default-keywords -k '$t.gettext'` results in an empty dictionary after extractions.

I believe this happens because the tokenizer only uses the `gettext` function name so the `$t.` is never part of it.

It would be nice if such cases were handled properly or if that's too complex, then defining a keyword containing a dot should result in an error instead.

**Comment by akx** [comment]
Yup, the tokenizer only got the last `name` of a dotted expression. The above PR adds support for dotted names when required. :)
