### ISSUE TITLE
Adding support for Bangla

### ISSUE THREAD

**Issue by auvipy** [python-babel/babel#152]
I would llike to know if bangla support is available in Babel? if not how can I work to add that and send a PR later?

**Comment by auvipy** [comment]
do i have to submit the issue in mailing list?

**Comment by benselme** [comment]
What is missing ? Bengla is in the CLDR, so it should already be supported in Babel. The locale is `bn`.
http://www.unicode.org/cldr/charts/27/summary/bn.html

**Comment by auvipy** [comment]
thanks for informing! my unicode knowledge is not that good

**Comment by sils1297** [comment]
@auvipy I'm closing this then as invalid :) Thanks for reporting anyways!
