### ISSUE TITLE
Collation support

### ISSUE THREAD

**Issue by remyroy** [python-babel/babel#154]
Collation support would be nice for comparing and sorting text. For Unicode, there is the [Unicode collation algorithm (UCA)](http://en.wikipedia.org/wiki/Unicode_collation_algorithm). The UCA has a default collation element table which is locale independent but there are also other collation element tables that are customized for different locale. Those customized collation element tables are part of CLDR. There is also [ISO 14651](http://en.wikipedia.org/wiki/ISO_14651) but it has less features compared to UCA.

Python already include two methods [strcoll](https://docs.python.org/3/library/locale.html#locale.strcoll) and [strxfrm](https://docs.python.org/3/library/locale.html#locale.strxfrm) in the locale standard library for both Python 2 and Python 3 that can be used for this but they depend on locales installed at the system level. They also require using the [locale.setlocale](https://docs.python.org/3/library/locale.html#locale.setlocale) method which is not thread safe on most systems and error prone. These methods depends on underlying C libraries which have known bugs on recent systems depending on which version was installed, they do not support unicode normalization and they are based on ISO 14651.

An alternative is to use [PyICU](http://pyicu.osafoundation.org/) with it's [Collator class](http://icu-project.org/apiref/icu4c/classicu_1_1Collator.html).

Another alternative is to use [pyuca](https://github.com/href/Python-Unicode-Collation-Algorithm) but it only supports the default collation element table for UCA and very few features.

The solutions for the text collation problem on Python are less than ideal and Babel is well positionned to fill this spot.

Here are a few related tickets from the old Trac for Babel:

* [#206 - Support Collation](http://babel.edgewall.org/ticket/206)
* [#112 - Add unicode tools to Babel](http://babel.edgewall.org/ticket/112)

**Comment by remyroy** [comment]
I've started reading [the reference document for UCA](http://www.unicode.org/reports/tr10). I'm trying to figure out how much work would be involved to implement it. I might give it a go in my free time on my fork.

**Comment by jadkik** [comment]
Why was this closed? Is this not something that belongs in Babel eventually?

If so, can you suggest an alternative? I suppose PyICU.
