### ISSUE TITLE
Сompiling *.mo files ignoring untranslated strings

### ISSUE THREAD

**Issue by elatonsev** [python-babel/babel#155]
It would be useful to add option to compile_catalog which avoid inclusion untranslated strings to *.mo file.
Something like use_fuzzy option for ignoring fuzzy translations.

It useful when you need made translations catalogs fallback - string that doesn’t translated in ukrainian catalog should be searched in russian catalog and than if it doesn’t translated will be returned itself in english.

Now if string isn’t translated it replaced with id while *.mo files compiling, and fallbacks doesn't work correctly. http://pylonsbook.com/en/1.1/internationalization-and-localization.html#fallback-languages

babel/messages/mofile.py
def write_mo(fileobj, catalog, use_fuzzy=False):
    ...
    if not message.string:
        msgstr = message.id.encode(catalog.charset)
    else:
        msgstr = message.string.encode(catalog.charset)

**Comment by yash14123** [comment]
On it.

**Comment by manasbedmutha98** [comment]
Is this still open?
