### ISSUE TITLE
A bug in support.Translations class prevent merge method to work with python 3

### ISSUE THREAD

**Issue by mbegoc** [python-babel/babel#162]
This code sample works well in python 2:

    from babel.support import Translations
    translations = Translations.load("path/to/translations", ["en"])
    other_translations = Translations.load("other/path/to/translations", ["en"])
    translations.merge(other_translations)

Switching to python 3 make it to throw an AttributeError ('filter' object has no attribute 'extend') at babel/support.py:590:

    self.files.extend(translations.files)

It turns out that self.files is set at babel/support.py:284:

    self.files = filter(None, [getattr(fp, 'name', None)])

The filter method returns a list in python 2 but python 3 version returns a kind of generator, which has not extend method. Make a list from the filter fix the issue, but I'm not sure what side effects it could have:

    self.files = list(filter(None, [getattr(fp, 'name', None)]))

**Comment by sils1297** [comment]
As pointed out in https://github.com/python-babel/babel/pull/92 this can be reproduced with the latest release.
