### ISSUE TITLE
Fix babel on python 3.5

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#171]
Especially 3.5 is important for the future, I wonder why 3.2 doesn't work as pypy probably iis a 3.2 version.

See https://github.com/mitsuhiko/babel/pull/169 for the build results of those builds.

**Comment by sils1297** [comment]
Related bug: https://github.com/mitsuhiko/babel/issues/168

**Comment by sils1297** [comment]
Ah thats pypy2. I recommend adding pypy3 too.

**Comment by sils1297** [comment]
uhm as for build against 3.2 there's the fundamental problem of unicode strings: see http://stackoverflow.com/questions/6625782/unicode-literals-that-work-in-python-3-and-2 for a potential solution.

**Comment by erickwilder** [comment]
@sils1297 
I don't really think that supporting Python 3.2 is really necessary. Official support was for Python 3.3 and I think we can move forward by just supporting 3.3+
What do you think?

**Comment by sils1297** [comment]
@erickwilder so the key "feature" of python 3.2 is that pypy3 only support the python 3.2 specification. Taking this into account, any project that does not support python 3.2 and python 2 will not run with pypy. For some applications like coala (:)) pypy makes totally sense because performance is relevant which is the main reason for us at coala to support python 3.2.

So the thing is that Babel is a very basic package and that all the restrictions it poses are inherited to its users. Babel is the only maintained pypi package that offers good gettext stuff AFAIK so this implies that any project using things like function annotations *and* wants to use i18n platform independently properly (-> Babel's the only thing possible) cannot be run with pypy.

So that's my view on python 3.2, I know it's sometimes painful but Windows support is worse ;).

**Comment by mitsuhiko** [comment]
Please don't make this run on 3.2.  This requires removing all unicode prefixes and this is going to just make a lot of stuff really ugly and complicated.  Nobody uses 3.2.

**Comment by mitsuhiko** [comment]
Also, I'm a hard -1 on changing the unicode literal behavior.  That part is non negotiable.

**Comment by mitsuhiko** [comment]
Also you are wrong. PyPy3 supports unicode literals just fine.

**Comment by sils1297** [comment]
@mitsuhiko alright, so only 3.5

**Comment by ericholscher** [comment]
It appears this is failing on Python 3.4 on Windows as well: https://ci.appveyor.com/project/ericholscher/sphinx-autoapi/build/1.0.5

**Comment by ericholscher** [comment]
```
=================================== ERRORS ==================================== 
_________________ ERROR collecting tests/test_integration.py __________________ 
tests\test_integration.py:9: in <module> 
    from sphinx.application import Sphinx 
.tox\py34\lib\site-packages\sphinx\application.py:37: in <module> 
    from sphinx.builders import BUILTIN_BUILDERS 
.tox\py34\lib\site-packages\sphinx\builders\__init__.py:23: in <module> 
    from sphinx.util import i18n, path_stabilize 
.tox\py34\lib\site-packages\sphinx\util\i18n.py:15: in <module> 
    from babel.messages.pofile import read_po 
.tox\py34\lib\site-packages\babel\messages\__init__.py:12: in <module> 
    from babel.messages.catalog import * 
.tox\py34\lib\site-packages\babel\messages\catalog.py:23: in <module> 
    from babel.dates import format_datetime 
.tox\py34\lib\site-packages\babel\dates.py:28: in <module>
    from babel.util import UTC, LOCALTZ
.tox\py34\lib\site-packages\babel\util.py:278: in <module>
    from babel import localtime 
.tox\py34\lib\site-packages\babel\localtime\__init__.py:21: in <module> 
    from babel.localtime._win32 import _get_localzone 
.tox\py34\lib\site-packages\babel\localtime\_win32.py:18: in <module> 
    tz_names = get_global('windows_zone_mapping') 
.tox\py34\lib\site-packages\babel\core.py:58: in get_global 
    _global_data = pickle.load(fileobj) 
E   TypeError: an integer is required (got type str) 
```

**Comment by ericholscher** [comment]
Hmm, I thought this was the bug for this error, as I have it in my history -- but perhaps I'm in the wrong place. Anyways, this is breaking Sphinx on Windows in Python 3.

**Comment by sils1297** [comment]
Closing in favor of https://github.com/python-babel/babel/issues/222
