### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#176]
Hey @erickwilder we'll probably want to set up some guidelines for contributions.

They need to be well reviewable and commit message should contain reasoning and be properly formatted IMO. We can almost copy guidelines from coala if you're good with that: http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/

Second, we'll need review, testing, documentation guidelines and so on. I have something like http://coala.readthedocs.org/en/latest/Getting_Involved/Review/ and http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Tests/ in mind.

**Comment by erickwilder** [comment]
Agree on creating contribution Guidelines, this makes the job of managing incoming issues/pull request easier.
Is there any other Pocoo-based project with some well stablished guidelines? Before looking at Coala I'm more inclined to follow something that's already "in the house".

What do you think?

**Comment by sils1297** [comment]
I'm fine as long as there are such guidelines. @mitsuhiko are there contribution guidelines for pocoo projects?

**Comment by mitsuhiko** [comment]
The styleguide is here: http://flask.pocoo.org/docs/0.10/styleguide/

For the rules that govern Babel I think I will make a document that set up some of the general hard requirements for how the project has been run so far so that it stays somewhat reasonable close to where it is design wise.

**Comment by erickwilder** [comment]
@mitsuhiko
Great. I'm waiting. Meanwhile we'll use our best judgement to approve contributions.

Thanks

**Comment by mitsuhiko** [comment]
Added this now: https://github.com/mitsuhiko/babel/blob/master/docs/dev.rst

Hope that helps.

**Comment by sils1297** [comment]
Basic guidelines are here, we can close this and add more as needed.
