### ISSUE TITLE
Add automatic releases to PyPI

### ISSUE THREAD

**Issue by sils** [python-babel/babel#194]
This will make it easier for people to get the latest and greatest version and makes them able to test unreleased bugfixes without needing to build from source - simply use `pip install --pre babel` for that.

Plan: let rultor do a development release on every merge to master.

**Comment by sils1297** [comment]
I've done some rultor testing and am stuck a bit with those failures: http://www.rultor.com/t/4721-128266162 with no time to correct it but something like that will probably work for merges.

Commits are the top two commits on sils1297/babel master: https://github.com/sils1297/babel

Then we'll do some script derived from https://github.com/coala-analyzer/coala/blob/master/.misc/deploy.pypi.sh on top to get the stuff deployed to pypi.

**Comment by sils1297** [comment]
For this to work @mitsuhiko either needs to give a PyPI user of mine access to the babel package or create a bash script that exports `PYPIUSER` and `PYPIPW`, encrypt this with `rultor encrypt -p mitsuhiko/babel .ci/rultor_secrets.sh` and add it to the repository. Be sure to not use `set -x` to keep the values hidden from the log.
