### ISSUE TITLE
Backport commits since 2.0

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#195]
@erickwilder can you go through commit history since 2.0 and backport where possible? Especially CI stuff needs backporting and of course bug fixes and that stuff. I'd love to have a PR to the 2.0 maintenance branch and we probably want another for things that apply to 1.0 although I'm not sure to what degree that has to be actively maintained.

**Comment by sils1297** [comment]
@erickwilder needs to be done as fast as possible and I'll be busy with GUADEC and GSoC administration stuff so I took the freedom to assign you.

**Comment by erickwilder** [comment]
Ok. But I do think that making pull requests on top of the 2.x branch still needs some code review. Can you at least take a look in them ?

**Comment by sils1297** [comment]
@erickwilder sure, assign me to the PR and please drop a comment on them so I'll get an email. You aren't accidentally at GUADEC are you?

**Comment by erickwilder** [comment]
@sils1297 
Sorry for the huge delay. I'm near a critical deadline of a project.
CI settings was backported in the #197 and we're near to merge #193 

Is there any other critical change that needs to be backported?

**Comment by sils1297** [comment]
I'm not able to determine that myself until September.

**Comment by erickwilder** [comment]
OK. Personally I would backport just critical bug fixes and features. What you think about this?

**Comment by sils1297** [comment]
Agreed.

2015-08-25 16:58 GMT+02:00 Erick Wilder <notifications@github.com>:

**Comment by etanol** [comment]
The backporting policy has been updated, so this can be closed, right?

**Comment by erickwilder** [comment]
:+1: I agree
