### ISSUE TITLE
wheels for babel

### ISSUE THREAD

**Issue by srkunze** [python-babel/babel#204]
Do you consider providing Python wheels for babel? cf. http://pythonwheels.com/

**Comment by erickwilder** [comment]
Hi @srkunze. Thank you for your feedback.

The library was a little stale in the past months. We're trying to get things done as soon as possible. Right now we're focused on reviewing open pull requests to give us a solid ground to keep the library as much updated as possible.

I do think that providing wheels is an important topic, but I can't see when this is gonna happen. We don't have any clear roadmap for the library now but your suggestion will be taken into account when we decide to create it.

Again, thank you

**Comment by sils1297** [comment]
@srkunze hey, I'll do a 2.1 release soon as I have access to pypi since today. This will include a wheel for sure.

See https://github.com/python-babel/babel/issues/224 for more information. Closing this.

**Comment by srkunze** [comment]
Great, thanks.
