### ISSUE TITLE
Add python 3.5 support

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#222]
Python 3.5 will be there soon and we should add CI for it and make sure it works.

Possible related issue: https://github.com/mitsuhiko/babel/issues/221

**Comment by akx** [comment]
Babel seems to work fine on my Windows x64 Python 3.5 setup.

**Comment by sils1297** [comment]
@akx cool, would you mind adding python 3.5 to the travis.yml and appveyor config so we have builds against that?
