### ISSUE TITLE
Upgrade CLDR to version 28

### ISSUE THREAD

**Issue by benselme** [python-babel/babel#226]
CLDR version 28 was released today:
http://blog.unicode.org/2015/09/cldr-version-28-released.html

We should upgrade to this new version.

**Comment by sils1297** [comment]
@benselme thanks for reporting. Could you do a PR?

Manpower's short currently, see https://github.com/mitsuhiko/babel/issues/227 for more info on that.

**Comment by sils1297** [comment]
Related: https://github.com/python-babel/babel/issues/165

If this gets done, we can close the other one also.

**Comment by etanol** [comment]
Moving the focus to #290
