### ISSUE TITLE
Docs: Expose gitter instead of IRC

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#235]
At least I am way more reliably available on https://gitter.im/python-babel/babel than on IRC and there any request will for sure be answered by me. We should point users to that instead of IRC or the mailing list.

**Comment by erickwilder** [comment]
Agreed.

**Comment by sudheesh001** [comment]
@sils1297 Looks like this is already fixed, the gitter link is available in the `README.md` file, Maybe this issue is good to close.

**Comment by sils1297** [comment]
Oh yeah I think I just forgot to close this - thanks!
