### ISSUE TITLE
The babel data files are not available in Babel-2.1.post20150925-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by jun66j5** [python-babel/babel#255]
I tried to install Babel-2.1 wheel package. However the wheel package has no `localedata/*.dat` files. Also `Babel-2.1.post20150925.tar.gz` on PyPI has no *.dat files.

```
$ pip install Babel
Collecting Babel
  Downloading Babel-2.1.post20150925-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 86kB 134kB/s
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /run/shm/babel-2.1/lib/python2.7/site-packages (from Babel)
Installing collected packages: Babel
Successfully installed Babel-2.1.post20150925
$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> babel.__version__
'2.1'
>>> from babel.core import Locale
>>> Locale.parse('en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dev/shm/babel-2.1/local/lib/python2.7/site-packages/babel/core.py", line 286, in parse
    language = get_global('language_aliases').get(language, language)
  File "/dev/shm/babel-2.1/local/lib/python2.7/site-packages/babel/core.py", line 55, in get_global
    _raise_no_data_error()
  File "/dev/shm/babel-2.1/local/lib/python2.7/site-packages/babel/core.py", line 27, in _raise_no_data_error
    raise RuntimeError('The babel data files are not available. '
RuntimeError: The babel data files are not available. This usually happens because you are using a source checkout from Babel and you did not build the data files.  Just make sure to run "python setup.py import_cldr" before installing the library.
```

**Comment by sils1297** [comment]
Thanks for mentioning. I'll remove the release ASAP. Maintainership changed
and apparently we have made an error during the release process. Thanks for
reporting.

**Comment by sils1297** [comment]
I will make the correct release within the next 1.5 hours approximately.
I'm truly sorry for any issues this caused.

2015-09-25 13:10 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

> Thanks for mentioning. I'll remove the release ASAP. Maintainership
> changed and apparently we have made an error during the release process.
> Thanks for reporting.

**Comment by sils1297** [comment]
The 2.1 release is removed from pypi, due to the heavy limitations of my
mobile internet connection, making the correct release will take more time
as indicated before.

2015-09-25 13:16 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:

> I will make the correct release within the next 1.5 hours approximately.
> I'm truly sorry for any issues this caused.
>
> 2015-09-25 13:10 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
>
>> Thanks for mentioning. I'll remove the release ASAP. Maintainership
>> changed and apparently we have made an error during the release process.
>> Thanks for reporting.

**Comment by sils1297** [comment]
fixed with the 2.1.1 release

```
$ python
Python 2.7.10 (default, Jul  5 2015, 14:15:43) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> babel.__version__
'2.1.1'
>>> from babel.core import Locale
>>> Locale.parse('en_US')
Locale('en', territory='US')
```

**Comment by jun66j5** [comment]
Thanks for the quick fix!

**Comment by sils1297** [comment]
@jun66j5 sure, sorry for breaking the release, this was really bad.

FWIW, we already have plans to automate the release process further to avoid such errors in the future, see https://github.com/python-babel/babel/issues/194 .
