### ISSUE TITLE
Update AUTHORS file and maintainers

### ISSUE THREAD

**Issue by sils** [python-babel/babel#261]
Hi, we should avoid @mitsuhiko getting emails from users thinking he is the maintainer. He has agreed that it's the best to name "The babel authors" as authors crediting everyone in the AUTHORS file.

**Comment by sils1297** [comment]
Oh and maybe we should write down a nice git command that writes down contributors for each release in the order of number of patches in the current release or so, I find this is a nice way to give explicitly credit to people like @etanol who really drive babel right now versus lazy maintainers like me.

**Comment by etanol** [comment]
As you prefer.  The command is a tempting alternative.  On the other hand, projects as big as Django still maintin the contributor list manually.

My preference is to have such a command: lazyness drives automation.

**Comment by sils1297** [comment]
I'm always for automation if the same thing can be achieved automating the task, pays off on long term. So, TODOs:

- [ ] Replace author mentions with "The Babel Authors"
- [ ] Add a script that regenerates the AUTHORS file and does a commit with that and the message `[GENERATED] Regenerate AUTHORS`.

**Comment by upman** [comment]
@sils1297 I'm working on this.
What do we do with author_email in `setup.py`?

**Comment by sils1297** [comment]
@upman we may just remove the field

**Comment by sudheesh001** [comment]
@sils1297 @etanol Is this still up for grabs ? I am wondering, why can't we use

`git shortlog -s -n` that'll give the right result that we're expecting ? It gives a neat well aligned text content too, for babel it shows.

```
   225	Christopher Lenz
   216	Armin Ronacher
    92	Alex Morega
    76	Aarni Koskela
    71	Felix Schwarz
    70	Lasse Schuirmann
    62	Pedro Algarvio
    61	Jeroen Ruigrok van der Werven
    28	Philip Jenvey
    26	benselme
    20	Isaac Jurado
    16	Tobias Bieniek
    14	Erick Wilder
    12	Jonas Borgström
     5	Michael Birtwell
     4	Alex Willmer
     4	Daniel Neuhäuser
     3	sudheesh001
     2	Kevin Deldycke
     2	Arturas Moskvinas
     2	Erik Romijn
     2	Hyunjun Kim
     2	Jun Omae
     2	Leonardo Pistone
     2	Lukas B
     2	Ryan J Ollos
     2	Sachin Paliwal
     1	Craig Loftus
     1	Florian Schulze
     1	masklinn
     1	srisankethu
     1	Matt Iversen
     1	Felix Yan
     1	Nick Retallack
     1	Eoin Nugent
     1	Dirkjan Ochtman
     1	Philip_Tzou
     1	Roman Imankulov
     1	Roy Wellington Ⅳ
     1	Alexander A. Dyshev
     1	Régis Behmo
     1	xen
     1	Sjoerd Langkemper
     1	Sven Anderson
     1	The Gitter Badger
     1	Thomas Waldmann
     1	David Stanek
     1	Todd M. Guerra
     1	astaric
     1	Jesús Espino
     1	Jeremy Weinstein
     1	Joseph Breihan
     1	Julen Ruiz Aizpuru
     1	James Page

```
