### ISSUE TITLE
Updating the CHANGES file - new concept

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#263]
@erickwilder @etanol the changes file is written to at almost every PR and is the main source for conflicts during merge/rebase. I think we should come up with a new strategy here.

How about: whenever some maintainer merges a PR, he changes the CHANGES file and commits that to a `feature/changes` branch which has a Pull Request open which we merge when we do the release? This could be even done via the GitHub UI if a merge is done while lacking a proper terminal.

**Comment by erickwilder** [comment]
Sounds good. We can give a try. :+1:

**Comment by techtonik** [comment]
Alternative workflow ifs to create `CHANGES.techtonik` files that are being merged into CHANGES during release.

**Comment by sils1297** [comment]
We could also just collect them on a wiki page *or* simply update the changes file when we're doing a release by crawling the commit history. I'm collecting changes here now: https://github.com/python-babel/babel/wiki/CHANGES

**Comment by akx** [comment]
The wiki page approach seems to work fine. Closing this as resolved with that method :)
