### ISSUE TITLE
Pofile parser can't handle multi-line obsolete IDs or Strings

### ISSUE THREAD

**Issue by nickretallack** [python-babel/babel#27]
Any multi-line obsolete message just comes out as "".

It should be obvious why, when you look at [this line](https://github.com/mitsuhiko/babel/blob/master/babel/messages/pofile.py#L222).  Every line of an obsolete string begins with a #, but every time the script sees a # it throws away all its state variables assuming it is probably starting a new message now, or accumulating occurrences and comments about one.

Here's a test case:
```
import babel.messages.pofile as pofile
from StringIO import StringIO

buffer = StringIO("""
#~ msgid ""
#~ "ID"
#~ msgstr ""
#~ "String"
""")

catalog = pofile.read_po(buffer)
assert catalog.obsolete.keys() == ['ID']
assert catalog.obsolete.values() == 'String'
```

**Comment by akx** [comment]
Closed via #429 :)
