### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by zackargyle** [python-babel/babel#280]
Hey guys,

We are using React for newer projects, and it would be great to have lexer support for JSX syntax. As an example, all three strings are not picked up. In one place only String 2 is picked up, where in another place String 1 and String 3 are picked up, but not String 2. Adding JSX support should fix the "randomness".
```
    <option value="val1">{ i18n._('String1') }</option>
    <option value="val2">{ i18n._('String 2') }</option>
    <option value="val3">{ i18n._('String 3') }</option>
```

Seems to not be consistent for `const` in ES6 classes as well.

**Comment by mitsuhiko** [comment]
I wonder if we can use babel (the js one) to parse it.

**Comment by zackargyle** [comment]
That's what I ended up doing in my jenkins job. Run it through babel, then extract. Wasn't too big of a deal, but build-in support could be nice.

**Comment by akx** [comment]
Adding rudimentary JSX support shouldn't be too hard. Working on it!

**Comment by akx** [comment]
@zackargyle If you're around, would you care to do a bit of code review on #332? :)
