### ISSUE TITLE
Babel does not support ISO 639-2 language codes 

### ISSUE THREAD

**Issue by albertvaka** [python-babel/babel#285]
Trying to call `Locale.parse` from an ISO 639-2 language code [1] like «ast» throws an `UnknownLocaleError`. 

Can you add support for these kind of three-letter language codes?

[1] http://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by sils1297** [comment]
> Can you add support for these kind of three-letter language codes?

We do try to look at PRs as fast as possible. That's usually not very fast. You're free to support us with your PR for this issue and with helping us reviewing PRs. If you're interested to help, come and sync with us at https://gitter.im/python-babel/babel .

**Comment by sils1297** [comment]
That sadly means that probably nobody from us will have time to fix this. :/

**Comment by albertvaka** [comment]
Sorry, false alarm. It actually is working :)

The script `download_import_cldr.py` already points to a CLDR that includes three-letter languages. It's not the latest CLDR (version 26 instead of 28), but it's up-to-date enough for me. I just had to uninstall and reinstall Babel to trigger the script again and now my locale-data directory is populated with all the ISO 639-2 languages.

Sorry again and thank you!

**Comment by sils1297** [comment]
No problem :)

2015-12-01 12:12 GMT+01:00 Albert Vaca <notifications@github.com>:

**Comment by jenstroeger** [comment]
I just ran into a similar issue when I used [ISO 638/2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) language codes:
```
>>> import babel
>>> babel.__version__
'2.8.0'
>>> babel.Locale("eng")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'eng'
>>> babel.Locale("en")
Locale('en')
>>> babel.Locale("ita")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'ita'
>>> babel.Locale("it")
Locale('it')
>>> babel.Locale("ger")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'ger'
>>> babel.Locale("de")
Locale('de')
```
@albertvaka, how did you use these language codes?

@sils, I don’t see them [documented](http://babel.pocoo.org/en/latest/) but it probably wouldn’t be difficult to add them?
