### ISSUE TITLE
CLDR parser is probably broken (invalid plural forms)

### ISSUE THREAD

**Issue by imankulov** [python-babel/babel#287]
While trying to import data from CLDR with babel I encountered some issues which I would like to share.

- Version 2.1.1 installed with pip returns invalid number of plurals at least for Turkish (tr) and Hungarian (hu). According to babel, both languages have only one form, while [in fact they have two](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html#hu): `one` and `other`.
- Version installed from git fixes the issue with Hungarian and Turkish, but gettext strings returned for at least Russian and Polish, contain forbidden variables. While gettext only accepts `n` as a variable, Babel rules contain `i` and `v` vars.

Attaching the gist with my testing script and my output: https://gist.github.com/imankulov/866660acdd90cb4004c7

Tested with following interpreter

```
Python 2.7.10 (default, Sep 23 2015, 04:34:14)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
```

I would appreciate any input. Thanks!

**Comment by sils1297** [comment]
@etanol have some time to look at this?

@imankulov thanks for reporting, we're seriously understaffed (nobody with actual time for this project is around :/) and are pretty much unable to do anything right now, if you would like to help you're very welcome and with a bit of luck @etanol has a hint.

**Comment by imankulov** [comment]
Would love to have some input to ensure that it's a bug indeed, and not me doing something wrong...

**Comment by akx** [comment]
I'll check this out in the course of #290 :)

**Comment by akx** [comment]
@imankulov: Preliminary investigation does seem to point to this being an actual bug, in particular `pluralRule` parsing entirely ignoring `other` rules. Removing the ignore condition uncovers plural rule parsing errors, so it's a slightly bigger issue...

**Comment by akx** [comment]
Actually, hmm, @imankulov: The `other` rules in the `hu` and `tr` locales have no associated expression, so it's expected that there is no `other` entry in `locale.plural_form.rules`.

**Comment by imankulov** [comment]
@akx thanks a lot for looking into this!

> The other rules in the hu and tr locales have no associated expression, so it's expected that there is no other entry in locale.plural_form.rules

I believe `other` rules don't have any expression in many (if not all) languages in CLDR, and thus I find it valid that there's no expression for `other`. Hungarian and Turkish rules look okay for me in version installed from git (but most likely they are broken in current stable version).

The git version has a different issue: rules at least in Russian and Polish contain "forbidden symbols" (`i` and `v` variables) in their gettext representation.

Hope I helped to clarify my issue. Thanks!

**Comment by akx** [comment]
@imankulov Thanks for the clarification. :) The CLDR database version (23.1) used by Babel 2.1.x is fairly old (from May 2013), so it's no wonder more recent Git versions, using CLDR 24/26/28 have fixed rulesets.

The forbidden symbol issue has a fix in #295; since Gettext doesn't support the floating-point variables, the patch makes them (`v`, `w`, `f`, `t`) compile into static zeroes and aliases `i`s to `n`s.

**Comment by imankulov** [comment]
@akx Great to know! Looking forward to having it merged :)

**Comment by sils1297** [comment]
@imankulov can you take a look at the commit (or did you do it already?)
