### ISSUE TITLE
format_date is wrong for Lithuanian long format

### ISSUE THREAD

**Issue by nhubanov** [python-babel/babel#288]
The correct case of the month when used with year and day in a date is genitive. Currently it's using nominative case. 
Example:

    from babel.dates import format_date
    from datetime import date

    format_date(date(2015, 12, 10), locale='lt_LT', format='long')
    u'2015 m. gruodis 10 d.'

Expected:

    format_date(date(2015, 12, 10), locale='lt_LT', format='long')
    u'2015 m. gruodžio 10 d.'

**Comment by akx** [comment]
I'll take a look at this in the course of #290.

**Comment by akx** [comment]
@nhubanov: This does not seem to be a problem with the current master (cc02cd1e936d632897). Could you confirm the version of Babel you were using?

**Comment by nhubanov** [comment]
I am testing with Babel 2.1.1, python 2.7.10 on OS X Yosemite 10.10.5

**Comment by akx** [comment]
Thanks, @nhubanov.

In that case I can confirm [it was an error in CLDR 23.1, the version used by Babel 2.1.1](http://unicode.org/cldr/trac/changeset/10669/trunk/common/main/lt.xml).

Versions since 546755f77b98a4ae4ddc29cb4c44b81cd88a31b1 (that use CLDR 24 or newer) will have fixed this.
