### ISSUE TITLE
Anything blocking a 2.2.0 release?

### ISSUE THREAD

**Issue by fschulze** [python-babel/babel#312]
Are there any blockers preventing a 2.2.0 release? Anything one can help with to make the release?

**Comment by sils1297** [comment]
Nope, @etanol @akx if you don't object I'll do a release today.

**Comment by akx** [comment]
I'm fine with it in principle.

Like I said in #292 (the CLDR 28 PR),

> I'd love to have more behavioral tests that ensure there aren't serious regressions in behavior (for example by way of mis-parsing the XML files), but I'm not quite sure where to source the data for that for several languages. For the time, the current tests will have to do.

and I guess that applies for the release too.

**Comment by akx** [comment]
Oh, and of course it'd be nice to get more features/bugfixes merged in before release (aside from my PRs, #265 looks nice?).

OTOH I do understand wanting a release featuring just CLDR 28 out.

**Comment by sils1297** [comment]
@akx how do we get those PRs reviewed? Do you think we should make our review policy less strict because of our lack of manpower?

**Comment by akx** [comment]
@sils1297 

No, imho a strict policy is better than subpar code in master.

I guess it's fine to do a 2.2.0 release with the current changes, then release more often as we get stuff reviewed. :)

**Comment by sils1297** [comment]
> There are some things (such as "edc5eb5 Add format_timedelta(format='narrow') support" is the first one I found) that don't seem to be listed in CHANGES, but I guess that's not a release blocker, since it's not a breaking change.

Changelog needs to be updated, will do the release after that.

**Comment by akx** [comment]
https://github.com/python-babel/babel/releases/tag/2.2.0 :)

:fireworks:

**Comment by fschulze** [comment]
Thanks!
