### ISSUE TITLE
currency_formats format changed between 2.1.x and 2.2

### ISSUE THREAD

**Issue by akx** [python-babel/babel#317]
The `None` key disappeared from `currency_formats` between 2.1.x and 2.2, making usages such as this https://github.com/shoopio/shoop/blob/5c5a9cd1193edcfe34693fc5b6c734a3f9528d8a/shoop/utils/i18n.py#L67 break when upgrading to 2.2.

I'm not sure if this is an actual bug, as the "solidity" of the CLDR-derived data dictionaries is admittedly a bit of a gray area API-wise.

**Comment by sils1297** [comment]
@akx can we work around that? If not can you add a note to `CHANGES`, make a PR for it?

**Comment by akx** [comment]
Hmm, I'm not sure what's a good workaround tbh. I can think of some ideas:

* Teach LocaleDataDict about some sort of fallback map (`{None: "standard"}` in this case) and make it use that in `__missing__`/`.get`, but if the grander plan is to get rid of LocaleDataDict altogether, as per @etanol 's implementation  (which sounds like a good idea simplicity-and-performance-wise), that won't do us much good. 
* Make `import_cldr` copy currency_formats' `standard` key to `None` during importing, which is simpler but sounds like an unfortunate redundancy.
  * If we go this route, it'd be a good idea to do a diff between the old locale data's and the new locale data's keys to see if there seem to be any other changes like this.
* Just shrug and note this in `CHANGES`. After all, the 2.1.x to 2.2 upgrade is bound to break tests in client code and change behavior, purely because the formats have been updated. (And considering this, should we actually do a semver major upgrade every time we switch to a new CLDR?)

**Comment by etanol** [comment]
This was a result of a CLDR 26 importing fix, see #201 and #203.  The example by @akx makes use of internal data structures, not the documented API.  We must try very hard to maintain API compatibility.  However, as with every Python package, users relying on internal details should assume the breakage risk.

Feel free to close this issue if the explanation is satisfactory.

**Comment by akx** [comment]
@etanol: `Locale.currency_formats` is a public API though (documented and not marked with an underscore).

As said though,

> I'm not sure if this is an actual bug, as the "solidity" of the CLDR-derived data dictionaries is admittedly a bit of a gray area API-wise.

Maybe it'd be a good idea to add an admonition to the CLDR data properties that their internal formats may change between releases.

**Comment by akx** [comment]
Self-assigning to remember to add that admonition.
