### ISSUE TITLE
update_catalog removes translators

### ISSUE THREAD

**Issue by ajaeger** [python-babel/babel#318]
Since the release of babel 2.2.0, we see in OpenStack that the header comments get modified and the list of translators gets removed:

```patch
--- a/neutron/locale/tr_TR/LC_MESSAGES/neutron.po
+++ b/neutron/locale/tr_TR/LC_MESSAGES/neutron.po
@@ -1,15 +1,11 @@
 # Turkish (Turkey) translations for neutron.
 # Copyright (C) 2015 ORGANIZATION
 # This file is distributed under the same license as the neutron project.
+# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
 #
-# Translators:
-# ADİL REŞİT DURSUN <ardursun@deltanoc.com>, 2015
-# Alper Çiftçi <alprciftci@gmail.com>, 2015
-# Andreas Jaeger <jaegerandi@gmail.com>, 2015. #zanata
-# OpenStack Infra <zanata@openstack.org>, 2015. #zanata
 msgid ""
 msgstr ""
```

neutron.pot file starts with, it's created with extract_messages:

```po
# Translations template for neutron.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 7.0.1.dev41\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
```

How can we keep the translators in here?

Reference:
https://review.openstack.org/#/c/263140/4/neutron/locale/tr_TR/LC_MESSAGES/neutron.po

**Comment by akx** [comment]
This is probably introduced by the otherwise seemingly harmless https://github.com/python-babel/babel/commit/e0e7ef168856bb431076cfe45f6c456d12091233 commit.

Are you able to patch your local Babel to revert that change and see if that fixes it? If so, I suppose we'll have to add a switch for this behavior...

**Comment by ajaeger** [comment]
Indeed, reverting that change does not cause the problem.

**Comment by akx** [comment]
Thanks for helping out there, @ajaeger. The fix is in the referenced PR #320.

**Comment by ajaeger** [comment]
Thanks a lot for the fast fix, @akx !

**Comment by sils1297** [comment]
@ajaeger would you mind reviewing it? Babels biggest issue is atm that we're not able to review stuff fast enough. Any help here would speed this up and be deeply appreciated! (Though @akx has to fix coverage first.)
