### ISSUE TITLE
Support more format for timezone 

### ISSUE THREAD

**Issue by item4** [python-babel/babel#325]
# Overview Description

I cannot use `XXXXX` or `ZZZZZ`

# Steps to Reproduce

See this `pycon` log

```pycon
>>> from babel.dates import format_datetime, get_timezone
>>> from datetime import datetime
>>> dt = datetime(2016, 1, 13, 7, 8, 35)
>>> tz = get_timezone('Asia/Seoul')
>>> dt = tz.localize(dt)
>>> format_datetime(dt, 'ZZZZZ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/babel/dates.py", line 618, in format_datetime
    return parse_pattern(format).apply(datetime, locale)
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/babel/dates.py", line 1192, in parse_pattern
    append_field()
  File "/Users/item4/.virtualenvs/lektor/lib/python2.7/site-packages/babel/dates.py", line 1156, in append_field
    % (fieldchar[0] * fieldnum[0]))
ValueError: Invalid length for field: 'ZZZZZ'
>>> format_datetime(dt, 'ZZZ')
u'+0900'
>>> format_datetime(dt, 'XXXXX')
u'XXXXX'
>>> format_datetime(dt, 'XXX')
u'XXX'
```

# Actual Results
`ValueError: Invalid length for field: 'ZZZZZ'` ... etc.

# Expected Results

`ZZZZZ` → `+09:00`
`XXXXX` → `+09:00`

# Reproducibility

100%, Repeat my code.

# Additional Information:

Python 2.7
Mac OS X

See [Date Field Symbol Table](http://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table) for spec.

**Comment by item4** [comment]
Why it labeled with invalid ?

**Comment by akx** [comment]
@gitmate-bot is being cranky, don't worry about it. (ping @sils1297 :) )

Thanks for the brilliantly specific bug report! 

It seems ZZZZZ was added in TR 35 Revision 23:

> Added documentation for the new date format pattern "ZZZZZ" (ISO 8601 time zone format) in Appendix F: Date Format Patterns and Appendix J: Time Zone Display Names . #3995]

and we simply don't have support for that yet.

If you feel like getting your hands dirty, we would appreciate a PR implementing this. :)

**Comment by item4** [comment]
@akx I consider make a PR. But I have question, where I can see version change log spec and limitation of python-babel supporting

**Comment by sils1297** [comment]
@akx I've done some label renaming so GitMate won't autoapply some labels that don't make sense like invalid.

**Comment by akx** [comment]
@item4:

The changelog is here: https://github.com/python-babel/babel/blob/master/CHANGES

What do you mean with "limitation of python-babel supporting"?

**Comment by item4** [comment]
@akx oh, sorry for my poor english :(

Can I know babel team's want's to support version of spec.

**Comment by akx** [comment]
@item4 Don't worry about it!

We're targeting Python 2.6, 2.7, 3.3, 3.4 and 3.5. Does that answer your question? :)
