### ISSUE TITLE
format_currency does not work with euros

### ISSUE THREAD

**Issue by rocambolesque** [python-babel/babel#326]
After upgrading to 2.2.0 from 2.1.1, format_currency does not work anymore.
Here's the code and the output from the 2 versions:
```
from babel import numbers
numbers.format_currency(1099, 'EUR', format='#,###', locale='fr')
2.1.1 output: '1\xa0099'
2.2.0 output: '1\xa0099,00'
```

The code behind format_currency has changed and now the format is not respected because the currency 'EUR' is not present in the 'currency_fractions' global, see here https://github.com/python-babel/babel/blob/master/babel/numbers.py#L329.

Is there a new way of doing this since 2.2.0?
I can't find my use case in the tests https://github.com/python-babel/babel/blob/master/tests/test_numbers.py#L246.

**Comment by akx** [comment]
Try adding the `currency_digits=False` kwarg.

@etanol: Maybe `currency_digits` should have no effect when an explicit format is passed in?

**Comment by etanol** [comment]
The old `format_currency` behaviour did not follow [the official recomendation from CLDR](http://unicode.org/pipermail/cldr-users/2014-November/000147.html) so it was changed, but with an option to force it.  As @akx mentioned, try with adding `currency_digits=False`.

Please review #127, #139 and #143.

**Comment by rocambolesque** [comment]
Ok thanks. FYI people using flask-babel can not upgrade to babel 2.2.0 as flask-babel 0.9 (last version to date) does not support this parameter.

**Comment by sils1297** [comment]
@akx you read my mind...

@rocambolesque see https://github.com/python-babel/flask-babel/issues/83 :)
