### ISSUE TITLE
Dead link on PyPI page to documentation

### ISSUE THREAD

**Issue by gregmuellegger** [python-babel/babel#331]
The link called "Package Documentation" on https://pypi.python.org/pypi/Babel directs to a dead end: http://babel.pocoo.org/en/docs/

Seems like http://babel.pocoo.org/en/ is the correct URL.

**Comment by sils1297** [comment]
@gregmuellegger thanks! I'll fix that for the next release.

**Comment by sils1297** [comment]
Apparently somebody uploaded an index.html for the documentation at some point that forwarde from pythonhosted to the URL, as there is the homepage link anyway it's quite useless though. I haven't found a way to remove that thing so far (though I'm kind of sick and can't think straight.) Maybe we have to replace it by a new index.html which forwards to the new domain.

**Comment by sils1297** [comment]
Hi, this is fixed now, thanks for reporting!
