### ISSUE TITLE
Correct link in Contributing.md

### ISSUE THREAD

**Issue by srisankethu** [python-babel/babel#345]
The link to Writing Good Commits is a deadend http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/ . Change it to http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits.html

**Comment by narayanacharya6** [comment]
Hey looks like the link needs to be updated again.
The current link is - 
https://coala.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html , which is a dead end.
Probably needs to change to - http://coala-red.readthedocs.io/en/latest/Getting_Involved/Writing_Good_Commits.html
