### ISSUE TITLE
CI/Appveyor: Do not build against all versions

### ISSUE THREAD

**Issue by sils1297** [python-babel/babel#377]
We're doing that on linux already, on windows we should only test 32 bit and 64 bit windows compatability, assuming that the version differences are the same. I think that's very sane and if we don't do that development will be horrible if there are a few more PRs.

**Comment by sils1297** [comment]
same is true for mac builds btw. they're horribly slow, no need to do them that for all versions which are essentially the same as on linux

**Comment by akx** [comment]
Regarding AppVeyor, I wonder if Python would run under WINE...
