### ISSUE TITLE
Strange new syntax for update --no-fuzzy-matching

### ISSUE THREAD

**Issue by jcristovao** [python-babel/babel#385]
Hi,

    pybabel update --help

    -N NO_FUZZY_MATCHING, --no-fuzzy-matching=NO_FUZZY_MATCHING
                        do not use fuzzy matching

Is this change of syntax intended? Shouldn't it be just `--no-fuzzy-matching`, without the equals?

This was using version 2.3.2
Tks

**Comment by akx** [comment]
Hi @jcristovao!

This is indeed a regression -- sorry about that! PR #386 will fix this.
