### ISSUE TITLE
2.3.3 distutils extract_messages misparses --keywords

### ISSUE THREAD

**Issue by ajaeger** [python-babel/babel#388]
We run in OpenStack to extract only the "_LW" keyword the following:

 python setup.py extract_messages --no-default-keywords \
            --keyword _LW \
            --add-comments Translators: \
            --input-dirs ${modulename} \
            --output-file ${POT}

With babel 2.3.3 the --no-default-keywords has no effect, the files contain far too much content.

**Comment by ajaeger** [comment]
To reproduce:
git clone git.openstack.org/openstack/cinder
cd cinder
python setup.py  extract_messages --no-default-keywords --keyword _LW --input-dirs cinder --output-file test233.pot

**Comment by ajaeger** [comment]
Sorry, couldn't come up with a self contained test quickly.

**Comment by akx** [comment]
@ajaeger: Can you see if it has an effect if you run via `pybabel` and not via distutils commands?

**Comment by ajaeger** [comment]
For smaller testcase:
$ mkdir test
$ cp cinder/service.py test/
$ python setup.py extract_messages --no-default-keywords --keyword _LW --input-dirs test --output-file test233.pot

Note that it does not include the _LW strings at all, only the default _

**Comment by ajaeger** [comment]
@akx 
pybabel extract --no-default-keywords -k '_LW' test -o test233.pot

Works fine for me, the content is as expected. Only _LW is extracted

**Comment by akx** [comment]
@ajaeger Okiedoke, thanks. 

I'd like to take this moment to point out that distutils' command mangling code is byzantine and strange, especially if one is used to modernities like click, argparse or even optparse... :)

**Comment by ajaeger** [comment]
@akx, just tested that Babel 2.3.2 handles this case fine.

**Comment by ajaeger** [comment]
@akx, thanks for looking into this nevertheless!

**Comment by akx** [comment]
Ah, the bug is actually not in `--no-default-keywords` being disrespected, it's in how the keyword string gets parsed.

I instrumented the extraction function to parse the args and die, and I get

```
python setup.py extract_messages --no-default-keywords --keyword _LW
{'_': None, 'L': None, 'W': None}
```

**Comment by ajaeger** [comment]
How did it work in 2.3.2 and earlier?

**Comment by akx** [comment]
2.3.3 changed that particular parsing code to do things differently to have the `pybabel` commands work correctly with multiple keywords (your issue #384), but unfortunately broke support for `distutils` arguments. In short

* versions 2.3.0..2.3.2 break multiple `-k`/`--keywords` arguments for `pybabel extract`
* version 2.3.3 breaks the single `-k`/`--keywords` argument accepted by distutils `extract_messages`

I'll try and get a bugfix in asap. Honestly I'm a little embarrassed by these.

**Comment by akx** [comment]
And really, there's a bit of a problem in that Distutils-based commands only support a single repetition of the same option, which is why you have to separate some options with spaces, some with commas, etc., for multiple options; the Optparse-based standalone pybabel command allows repetitions of the same option for the same effect.

**Comment by akx** [comment]
@ajaeger: Would you be able to test that all of Openstack's usecases (since apparently some of your processes use `pybabel` as evident from #384 and others use the distutils-based commands as evident here) work with the code in https://github.com/python-babel/babel/pull/389?

**Comment by ajaeger** [comment]
@akx I can test the common two use cases, just tell me if you have something to test.

I've wrote also a patch to use only pybabel in OpenStack infra scripts - one issue less to test. Let's see what the reviewers think.

**Comment by ajaeger** [comment]
Sorry, misread your notice, @akx. You already told me what to test. I did some testing and it looks fine to me. Thanks!
