### ISSUE TITLE
Fail to import latest CLDR data

### ISSUE THREAD

**Issue by aronbierbaum** [python-babel/babel#391]
While using babel-2.3.2 I tried to download and import the latest CLDR data I get the following KeyError while processing `bs.xml`. It appears that the issue is caused by the fact that the `cldr\core-28\common\main\bs.xml` file contains a comment above the `<eraNames>` node.

```
python C:\source\babel-2.3.2\scripts\import_cldr.py C:\source\babel-2.3.2\cldr\core-28\common

Processing bs.xml (Language = bs; Territory = 001)
Traceback (most recent call last):
  File "C:\source\babel-2.3.2\scripts\import_cldr.py", line 876, in <module>
    main()
  File "C:\source\babel-2.3.2\scripts\import_cldr.py", line 193, in main
    dump_json=bool(options.dump_json)
  File "C:\source\babel-2.3.2\scripts\import_cldr.py", line 207, in process_data
    _process_local_datas(sup, srcdir, destdir, force=force, dump_json=dump_json)
  File "C:\source\babel-2.3.2\scripts\import_cldr.py", line 408, in _process_local_datas
    parse_calendar_eras(data, calendar)
  File "C:\source\babel-2.3.2\scripts\import_cldr.py", line 607, in parse_calendar_eras
    width_type = NAME_MAP[width.tag]
KeyError: <built-in function Comment>
```

```xml
<eras>
   <!-- Copied from sr_Latn -->
   <eraNames>
   ...
   </eraNames>
</eras>
```

I believe a simple fix would be to change the following:

```python
for width in calendar.findall('eras/*'):
```

to

```python
for width in calendar.findall('eras/era'):
```

**Comment by jtwang** [comment]
I can reproduce this error if I run `make clean-cldr && make import-cldr` in an env with lxml (in Python 2.6, not sure if that makes a difference).
The error does not occur in an env without lxml (ie script uses xml instead).

Error occurs with 5aa21f9 (2.3)
Error does not occur with 327bcdf (2.2)

Changing the XPath does fix the script (diff below), but I also got really strange test failures. :/ I'll poke around some more and also see if I can track down what introduced the script failure.

@aronbierbaum - can you verify that you have lxml installed? Also, which version of Babel were you using previously where the script succeeded.

{code}
~/babel (bec1151...) $ git diff
diff --git a/scripts/import_cldr.py b/scripts/import_cldr.py
index f684de3..3a7604d 100755
--- a/scripts/import_cldr.py
+++ b/scripts/import_cldr.py
@@ -603,7 +603,7 @@ def parse_calendar_quarters(data, calendar):
 
 def parse_calendar_eras(data, calendar):
     eras = data.setdefault('eras', {})
-    for width in calendar.findall('eras/*'):
+    for width in calendar.findall('eras/eraNames'):
         width_type = NAME_MAP[width.tag]
         widths = eras.setdefault(width_type, {})
         for elem in width.getiterator():
{code}

**Comment by aronbierbaum** [comment]
I'm also using lxml, I should have included that in my original message. I have just started working with Babel so I have not had it work successfully before. Please let me know if you want be to do any additional testing.

**Comment by jtwang** [comment]
@akx has given his blessing to revert 9b5c7f3678167f03ec39fd1c25f98d0e0d41621f, which introduced lxml as an optimization.

@aronbierbaum - if you wouldn't mind testing after this is pushed, that'd be awesome! For now, nothing needed, thanks for asking. <3
