### ISSUE TITLE
Babel-2.3.4 not available from deterministic download URL

### ISSUE THREAD

**Issue by nphilipp** [python-babel/babel#395]
Hi, the latest release 2.3.4 isn't available from https://pypi.python.org/packages/source/B/Babel/Babel-2.3.4.tar.gz like previous versions---to download it I have to go to https://pypi.python.org/pypi/Babel/2.3.4 and manually download from the seemingly random URL linked from there: https://pypi.python.org/packages/6e/96/ba2a2462ed25ca0e651fb7b66e7080f5315f91425a07ea5b34d7c870c114/Babel-2.3.4.tar.gz

**Comment by akx** [comment]
This is a change that has occurred on PyPI, and it's not something we can touch.

See the Warehouse commit: https://github.com/pypa/warehouse/commit/43e9a7bb0c1cf3c98bc32221355c49bbe5015c68

However, the URL is not random -- the URL you pasted is and will be the canonical PyPI tarball URL for 2.3.4.

**Comment by akx** [comment]
Closing this as resolved.

So anyway, it seems future PyPI file URLs will always be hash-based, in case that affects your scripts/infrastructure/whatnot. :)

**Comment by nphilipp** [comment]
What I meant is, I can't know the URL of the tarball without visiting https://pypi.python.org/pypi/Babel  and scraping it from there -- it's not deterministic and that makes it hard to use in e.g. RPM spec files. Anyway, it seems the upcoming PyPi 2.0 will have redirects from the old-style URLs, as can be tested by downloading the tarball from the test site: https://pypi.io/packages/source/B/Babel/Babel-2.3.4.tar.gz
