### ISSUE TITLE
pybabel extract --no-wrap feature doesn't work (pybabel 1.2)

### ISSUE THREAD

**Issue by cprcrack** [python-babel/babel#40]
Using _--no-wrap_ on the pybabel command line tool doesn't seem to work. My _msgstr_ strings in the _messages.po_ files are split into several lines. _--width_ also seems to be omitted, because I tried using a width such as 10000 without any difference.

Example command:

```
pybabel extract --mapping=./pybabel.cfg --no-wrap --output=./locale/messages.pot ./
```

**Comment by rahulsahni06** [comment]
> I cannot reproduce that. Do you have a way for me to test this? (Easiest would be to make a github repo with a test file, and a Makefile to run that runs pybabel the way it breaks for you).
> 
> Notice that strings that are already broken into lines with `\n` will continue to be broken into lines in `.po` files. That is intentional but we can probably consider adding an option to change that.
> 
> Temporarily closed as WORKSFORME.

Is there any option now to turn off the line breaking due to `\n`? I am trying to extract a string with `\n` and like you said it always breaks the line.
