### ISSUE TITLE
Hang when extracting messages

### ISSUE THREAD

**Issue by rlam3** [python-babel/babel#401]
PYBABEL HANGS ...? HOW TO DEBUG?

The following commpand is:
```bash
pybabel extract -F babel.cfg -k lazy_gettext -o messages.pot my_app_folder
```

The processes has been hanging for a while and I don't know how to debug... Is there an option for this? 

Even when i remove everything from the file or comment out the whole .py file that it is hanging on... the process is still hanging...

**Comment by rlam3** [comment]
So I looked into pybabel's code and it looks like it is hanging on this particiular loop in frontend.py

After the catalog.add method it looks back and it hangs... Please let me know what we can do the relieve of this problem? Does there need to be a break some where here?

```python
                for filename, lineno, message, comments, context in extracted:

                    if os.path.isfile(path):
                        filepath = filename  # already normalized
                    else:
                        filepath = os.path.normpath(os.path.join(path, filename))

                    catalog.add(message, None, [(filepath, lineno)],
                                auto_comments=comments, context=context)

```

**Comment by akx** [comment]
I don't think it's actually _hanging_ -- maybe add `print(filename, lineno, message, comments, context)` within that loop's body to see if it somehow manages to find an infinite amount of messages or something?

**Comment by rlam3** [comment]
@akx How do I find if there is infinite amount of messages? 

From what I've been trying around... it extracts fine as an individual module and file.. Its just doesn't like the fact that it is grouped with other modules together upon extraction...?

```
pybabel -v extract -F babel.cfg -k gettext -o messages.pot my_app/folder/module 

extracting messages from my_app/my_module/__init__.py
extracting messages from my_app/my_module/forms.py
extracting messages from my_app/my_module/views.py
writing PO template file to messages.pot
```

**Comment by rlam3** [comment]
I think it is hanging/running in the background for such a long time because it is looking at all the subdirectories of node_modules... is there a way to prevent babel from subdirectories? I've tried using the following but it seems like it is still going through all of them. 

```
[ignore: **/static/**.*]
```

**Comment by rlam3** [comment]
How should one be able to strictly ignore folders? OR How should one be able to specify which folders to look into?

[ignore: static/**.*]

When ignore happens.. Why does another method able to look into the ignored pattern? This doesn't make sense... 

This is not an ideal workaround...:
```yml

#babel.cfg
[python: mod1/**.py]
[python: mod2/**.py]
[python: mod3/**.py]
```

Reference: 
https://github.com/python-babel/babel/issues/124

**Comment by akx** [comment]
Adding `ignore` stanzas won't unfortunately make Babel not even recurse into those directories; checking file patterns against the extractor configuration is done separately.

For a quick patch in your local installation of Babel, you can add `or subdir == "node_modules"` to [the `if` statement in this segment here](https://github.com/python-babel/babel/blob/8b5e5b7131ef6cc49f7ad7fa27aa61e8b3a328fc/babel/messages/extract.py#L140-L142). (That particular segment is actually what causes #53, just pointing that out here.)

**Comment by akx** [comment]
I removed the bug label because this isn't an actual bug in Babel.

**Comment by rlam3** [comment]
@akx Thanks for the reply akx but could you please go more in depth on what you mean b subdir? Could you please show me an example of a babel.cfg using it? Thanks.

**Comment by akx** [comment]
@rlam3 

If you patch the linked segment,

```python
    for root, dirnames, filenames in os.walk(absname):
        for subdir in dirnames:
            if subdir.startswith('.') or subdir.startswith('_'):
                dirnames.remove(subdir)
        dirnames.sort()
        filenames.sort()
        for filename in filenames:
```
to read
```python
    for root, dirnames, filenames in os.walk(absname):
        for subdir in dirnames:
            if subdir.startswith('.') or subdir.startswith('_') or subdir == 'node_modules':
                dirnames.remove(subdir)
        dirnames.sort()
        filenames.sort()
        for filename in filenames:
```

Babel will not even recurse into `node_modules` directories.

There is currently no way of doing this via `babel.cfg` or command line parameters, but it's definitely something to put on the roadmap.

**Comment by akx** [comment]
Closing -- #402 will serve as a proper fix for this behavior.
