### ISSUE TITLE
Add `--ignore-dirs` or similar to `extract`

### ISSUE THREAD

**Issue by akx** [python-babel/babel#402]
See #53, #253, #401, #124.

Implementation idea:
- Add `directory_filter` callable arg to `extract_from_dir()`; this would be used instead of the hard-coded `if subdir.startswith('.') or subdir.startswith('_'):`
- Generate a directory filter callable from an `--ignore-dirs` argument, if passed in the CLI

**Comment by rlam3** [comment]
Looking forward to this patch to ignore certain directories/subdirectories.
