### ISSUE TITLE
Extract: docstrings lie

### ISSUE THREAD

**Issue by akx** [python-babel/babel#403]
* `messages.extract()`:
  * Docs say: *This function returns tuples of the form ``(lineno, message, comments)``.*
  * Yields 4-tuples `(lineno, messages, comments, context)`
* `messages.extract_from_file()`:
  * Docs say: *This function returns a list of tuples of the form ``(lineno, funcname, message)``.*
  * Returns a list of 4-tuples `(lineno, messages, comments, context)` (from `extract`)
* `messages.check_and_call_extract_file()`:
  * Does not document what it returns
  * Yields 5-tuples `(filename, lineno, messages, comments, context)`
* `messages.extract_from_dir()`:
  * Docs say: *This function generates tuples of the form ``(filename, lineno, message, comments, context)``.*
  * Actually does exactly that!

**Comment by ztane** [comment]
+1 I had to actually look into source code on how to write an extractor that properly returns context and plurals. Fix the pocoo docs as well.
