### ISSUE TITLE
NumberPattern.pattern does not preserve original pattern

### ISSUE THREAD

**Issue by jtwang** [python-babel/babel#407]
It basically keeps the positive format only.

```
>>> babel.numbers.parse_pattern(u'¤#,##0.00;(¤#,##0.00)').pattern
u'\\xa4#,##0.00'
```

Ideally, `pattern` would be `'¤#,##0.00;(¤#,##0.00)'`

This makes it difficult to copy/recreate an existing NumberPattern object.

Also, `repr()` uses `self.pattern`, so `repr(parse_pattern(u'¤#,##0.00;(¤#,##0.00)'))` returns the same thing as `repr(parse_pattern(u'¤#,##0.00'))`, which is misleading.

**Comment by akx** [comment]
Fixed in #414 :)
