### ISSUE TITLE
Regression on javascript extraction on v2.3

### ISSUE THREAD

**Issue by gsakkis** [python-babel/babel#416]
It seems like after upgrading to 2.3, some strings in minified javascript files are not extracted anymore. Is this a known bug?

**Comment by akx** [comment]
Not a bug I'm aware of -- sorry!

Do you have an example of a JavaScript file which fails extraction (or preferably a minimal test case that reproduces the problem), and what the expected output is?

I have an inkling this is related to #310 and friends.

**Comment by gsakkis** [comment]
I don't have a minimal test but I uploaded the original [here](https://www.dropbox.com/s/ip6oyp7rn8l41ax/stylect.js?dl=0), along with the output for [2.2.0](https://www.dropbox.com/s/kfkexsur5xvnpsv/messages-2.2.0.po?dl=0) and [2.3.4](https://www.dropbox.com/s/d4sgpodr9ex1p03/messages-2.3.4.po?dl=0). As you can see some (but not all) strings are missing from the latter.
