### ISSUE TITLE
get_timezone_name returning '∅∅∅' (CLDR-'no inheritance marker') as timezone. Babel 2.3.4/Python 2.7.7

### ISSUE THREAD

**Issue by stringtheory** [python-babel/babel#428]
`get_timezone_name` is returning `'∅∅∅'`  (3 empty set unicode characters) for several english locales, including `en_GB` and `en_IE`. The same results occur when using the `format_time` method. This only happens with the short format. 

**Steps to Reproduce & Actual Results:**

```
>>> tz = pytz.timezone('America/Los_Angeles')
>>> t = tz.localize(datetime(2016,1,6,7))
>>> print dates.format_time(t, format='long', locale='en_US')
7:00:00 AM PST
>>> print dates.format_time(t, format='long', locale='en_GB')
07:00:00 ∅∅∅
>>> print dates.get_timezone_name(t, width='short', locale='en_US')
PST
>>> print dates.get_timezone_name(t, width='short', locale='en_GB')
∅∅∅
```

**Expected Results:**

From the docs: "Note that short format is currently not supported for all timezones and all locales. This is partially because not every timezone has a short code in every locale. In that case it currently falls back to the long format."

```
>>> print dates.format_time(t, format='long', locale='en_GB')
07:00:00 Pacific Standard Time
>>> print dates.get_timezone_name(t, width='short', locale='en_GB')
Pacific Standard Time
```

**Additional Information:**

In `get_timezone_name` - putting a breakpoint on 
https://github.com/python-babel/babel/blob/master/babel/dates.py#L645

I get the following results:

```
metazone_info['short']['generic'] = u'\u2205\u2205\u2205'
metazone_info['short']['daylight'] = u'\u2205\u2205\u2205'
metazone_info['short']['standard'] = u'\u2205\u2205\u2205'
```

According to the CLDR, this is the 'no inheritance marker' when doing a lookup on metazone data. 
http://www.unicode.org/reports/tr35/tr35-dates.html#Metazone_Names

"If a given short metazone form is known NOT to be understood in a given locale and the parent locale has this value such that it would normally be inherited, the inheritance of this value can be explicitly disabled by use of the 'no inheritance marker' as the value, which is 3 simultaneous empty set characters ( U+2205 )."

To best align with the babel API docs, in the case where the CLDR data contains the 'no inheritance marker', it feels like the long form should be returned.

**Comment by akx** [comment]
Thanks for the excellent bug report, @stringtheory! #433 has a fix for this.

**Comment by stringtheory** [comment]
Tks for fixing!
