### ISSUE TITLE
collated sorting

### ISSUE THREAD

**Issue by sbi** [python-babel/babel#445]
I wonder whether babel should feature collated sorting. Sorting according to a locale's rules is a pretty common operation, besides translating and formatting things appropriately. CLDR apparently includes collation information, according to their website. Using PyICU sucks, it's essentially undocumented (well, PyICU's docs point to the official ICU documentation, which is... enterprisey, to put it nicely) and requires libicu to be installed. Has anyone tried this before? I'd be willing to work on this if there's no major objection.

**Comment by akx** [comment]
Have you seen https://github.com/jtauber/pyuca ?

**Comment by sbi** [comment]
@akx I haven't. Sweet! That makes this issue pretty pointless... I'm sorry for not doing more research before!

**Comment by akx** [comment]
No worries -- I mean, seriously, thanks for creating the issue in the first place, to bring attention to collated sorting in Python!

As a semi-related aside, to be honest I'm personally starting to think Babel should shed all the gettext-related bits and just concentrate on dealing with the things it does exceptionally well :)
