### ISSUE TITLE
Locale.parse cannot parse the locale 'xh' (xhosa)

### ISSUE THREAD

**Issue by hmpf** [python-babel/babel#451]
# Steps to reproduce:

```
from babel.core import Locale

Locale.parse('xh')
```
# Actual Results

```
    File "<censored>/.virtualenvs/test/lib/python3.5/site-packages/babel/core.py", line 333, in parse
        raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'xh'
```
# Expected Results

A locale object for `xh` that can be understood by `babel.messages.catalog.Catalog`.
# Reproducibility

Always
# Addition information:

This is for babel 2.3.4 as installed with pip and run on python 3.5.

It falls off at the final line (333): `raise UnknownLocaleError(input_id)`

Debug-by-assert shows that the first  `get_global('likely_subtags')` spits out `'xh_Latn_ZA'` which is then not handled by `_try_load_reducing(parse_locale(likely_subtag))`. The next attempt at `parse_locale` spits out `('xh', 'ZA', 'Latn', None)` which `_try_load_reducing` again interprets as None.

I'm assuming this is because there are no files prefixed with `xh` in `locale-data`?

I'm trying to load and write po-files, but it looks like I can't use babel to set the locale-header on them.

Would it at least be possible to raise another error than a generic UnknownLocaleError?

http://www.unicode.org/cldr/charts/23/summary/xh_ZA.html

**Comment by jtwang** [comment]
Yep, you're correct in that the version of the CLDR we use ([v28](http://www.unicode.org/repos/cldr/tags/release-28/common/main/)) doesn't contain definitions for xh or its dialects. Same for trunk. What's strange is that your link above shows that it existed at some point (looks like the last version that contained it was [v25](http://www.unicode.org/repos/cldr/tags/release-25/common/main/)). It's mentioned in the supplementary data for v28 though. Weird!

I don't have time right now to dig through the [release notes for v26](http://cldr.unicode.org/index/downloads/cldr-26), but there might be something in there that explains why this was dropped. There could be something in the CLDR that "redirects" the locale that I don't know about (and neither does Babel). (There's lots in the CLDR that I haven't looked at, so this is totally possible :)

In the meantime, the exception is correct IMO - the CLDR and thus babel doesn't have locale data for xh so it is, technically, unknown.

As a workaround, you could grab the .xml files from v26 and generate the xh .dat files manually (see [import-cldr](https://github.com/python-babel/babel/blob/master/Makefile#L20), as a starting point). I believe most xml schema changes between v26-28 will be mostly compatible with only minor tweaks needed in the v26 xml files.

**Comment by hmpf** [comment]
I've used the contact form at CLDR to ask, maybe it will be back for the next version.

The thought about another error message is that babel supports it half way. Enough to be able to look it up but not enough to make a Locale object because the .dat-files are missing. That's different from not being able to even look it up, for instance due to a typo.

**Comment by hmpf** [comment]
Answer from the CLDR:

> Hello.
> 
> Thank you for your interest in Unicode.
> 
> I sent your report to the CLDR team. They report that "xh" was moved from main to "seed" after V26 because there was not enough confirmed data.
> 
> There was some activity in V30, but there is not enough coverage for it to be moved back to the main directory.
> 
> For more information about CLDR and how you can access the "xh" data in the repository, please see: http://cldr.unicode.org/
> and
> http://cldr.unicode.org/index/downloads
> 
> The current trunk "xh" data itself can be retrieved here if you need it:
> http://www.unicode.org/repos/cldr/trunk/seed/main/xh.xml
> 
> I hope that helps.

**Comment by jtwang** [comment]
Oh hey, cool! I didn't think they'd respond that quickly. 😮  Thanks for following up on this! And, yeah, the Babel error could probably be more explicit about the exact failure.

If you need help with the workaround for getting xh loaded into Babel, poke me in the gitter channel. :)

**Comment by valentin-p** [comment]
Can I work on this improvement?
I could create a NotFoundLocaleDataError when the language is registered in the global dictionary but the locale data file does not exist.
I can do a PR soon.

**Comment by Geno117** [comment]
Just checking. Should this be closed By now?

**Comment by mattany** [comment]
> Just checking. Should this be closed By now?

+1

**Comment by akx** [comment]
Yep.

```
>>> import babel
>>> print(babel.Locale.parse('xh').get_language_name('xh'))
isiXhosa
```
