### ISSUE TITLE
Regular expression flags warning in Python 3.6

### ISSUE THREAD

**Issue by rudolphfroger** [python-babel/babel#467]
Babel with Python 3.6 issues a DeprecationWarning at import time:

```
site-packages/babel/plural.py:301: DeprecationWarning: Flags not at the start of the expression \s+(?u)
site-packages/babel/localtime/_unix.py:8: DeprecationWarning: Flags not at the start of the expression ^Time Zone: (.*)$(?m (truncated)
```

Relevant Python 3.5 docs about regular expression flags:

> It should be used first in the expression string, or after one or more whitespace characters. If there are non-whitespace characters before the flag, the results are undefined.

Python 3.6 docs:
>  Flags should be used first in the expression string.

**Comment by akx** [comment]
This seems to have been fixed in f89f48795fdbed07c51aa897eca590a05eb4b746 (Babel 2.4+).
