### ISSUE TITLE
Bad regexp escape in babel.plural

### ISSUE THREAD

**Issue by jwilk** [python-babel/babel#472]
`babel/plural.py` contains the following line:
```python
    ('ellipsis', re.compile(r'\.{2,3}|\u2026', re.UNICODE))  # U+2026: ELLIPSIS
```
But `\uXXXX` escape sequences in regexps were added only in Python 3.3.
In earlier versions, `\u` stands for literal `\u`.
In other words, in Python 2.X this line is equivalent to:
```python
    ('ellipsis', re.compile(r'\.{2,3}|u2026', re.UNICODE))
```
...which is certainly not what you wanted.

NB, the `re.UNICODE` flag affects only semantics of `\w`, `\W`, `\b`, `\B`, `\d`, `\D`, `\s` and `\S`, so it is no-op here.

The dubious regexp was found using [pydiatra](https://github.com/jwilk/pydiatra).

**Comment by akx** [comment]
Babel no longer supports Python 2.x, so this is dealt with.
