### ISSUE TITLE
TypeError: Unxpected value for identifier: b'en'

### ISSUE THREAD

**Issue by zhangjiajie023** [python-babel/babel#475]
centos 6.5
python 3.5.2
Flask-Babel 0.11.1
babel 2.3.4

1. when in my centos6.5 virtual machine, it works fine, not exists this error.
2. when in a server (centos6.5 too), occurs this error.

In what conditions the str `en` is transformed to `b'en'` ? 
tks...

**Comment by akx** [comment]
Hi @zhangjiajie023 – this sounds like an I/O encoding problem if it doesn't occur on your local setup.

A little more traceback would be appreciated (and more information on where you get that `'en'` string in the first place), but assuming I'm correct with my hypothesis that it's an encoding thing, can you check what the `locale` command outputs on both systems?

Also, how are you running your app?

**Comment by zhangjiajie023** [comment]
@akx when i debug my app，and track to `babel/core.py`:
```
elif not isinstance(identifier, string_types):
            raise TypeError('Unxpected value for identifier: %r' % (identifier,))
```
the `identifier` is str-type, and no error.

The i packed my app as `.whl`, install on centos6.5-virtual-machine and centos6.5-server individually. 
`Babel` is downloaded and installed by pip.  
App is based on flask-appbuilder. 
In my `config.py` `BABEL_DEFAULT_LOCALE = 'en'`

Do you mean the value of `locale = _try_load(parts)` ? it's `{Locale}en`

**Comment by akx** [comment]
Can you add `print(os.environ)` (or similar) to your `config.py` and make sure the `LANG` and `LC` variables are correct there, just to make sure the environment is what you expect even with the user that's running the application?

**Comment by zhangjiajie023** [comment]
@akx hi, i found it's caused by my chrome (maybe the cache). I changed to edge or reopen chrome, app works fine. But still make me puzzled .
Tks for your help

**Comment by akx** [comment]
That's certainly strange.

Closing this since you found a solution of sorts :)
