### ISSUE TITLE
ASSIGNMENT: Contribution, new features, documentation (Uni-class project)

### ISSUE THREAD

**Issue by alevas** [python-babel/babel#477]
Good afternoon Babel,

I am a student of the Athens University of Economics and Business, Department of Management Science & Technology. In the context of the Software Engineering in Practice course I am attending this semester, I must choose a project to contribute in it's source code.

I would like to contribute to Babel, work on developing new features, contribute to the documentation or anything else you may have to suggest!

Thank you in advance.

Your sincerely,
Alexandros Vasileiou

**Comment by akx** [comment]
Hi Alexandros!

If you'd like, you could look at the [`difficulty/low` issues](https://github.com/python-babel/babel/issues?q=is%3Aopen+is%3Aissue+label%3Adifficulty%2Flow+no%3Aassignee) or if you feel like doing some code review, there are [several PRs](https://github.com/python-babel/babel/pulls?q=is%3Aopen+is%3Apr+label%3A%22process%2Fpending+review%22) that could use some.

Don't hesitate to ping me if you need a hand -- I should really become more active about the project :)
