### ISSUE TITLE
how to translate the string called by markdown

### ISSUE THREAD

**Issue by zhangjiajie023** [python-babel/babel#484]
Assume i have a string to be translated:
```python
utils.markdown(
"A link [SqlAlchemy docs](http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls)", True)
```
I changed to:
```python
utils.markdown(lazy_gettext(
"A link [SqlAlchemy docs](http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls)"), True)
```
and add the translation to message.po:
```po
msgid "A link [SqlAlchemy docs](http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls)"
msgstr "链接 [SqlAlchemy docs](http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#database-urls)"
```
then compiled, but don't work. So how to translate the string called by markdown?

**Comment by akx** [comment]
Hi!

There is no function called `lazy_gettext` in Babel. For that reason, can I ask for clarification?

* Which frameworks, etc. are you using?
* Where is your `message.po`/`.mo`, and how are you activating it in your particular framework?

Other than that, I don't see any reason why the code wouldn't work.

**Comment by akx** [comment]
Closing as abandoned.
