### ISSUE TITLE
Support Spaces in Mapping File

### ISSUE THREAD

**Issue by djtm** [python-babel/babel#496]
I can't use spaces in the mapping file.
Below works perfectly inside jinja2. However pybabel ignores spaces in the setting (as jinja without above configuration section).
e.g. 

- Quotes

```
variable_start_string="{{ "
```
becomes `""{{ ""` -> added quotes -> not working

- Space at the end
```
variable_start_string={{ 
```
becomes `"{{"` -> space missing -> not working

- Backslash escape
```
variable_start_string={{\  # empty space at the end
```
becomes `"{{\"` -> missing space, backslash preserved.

Any ideas?

**Comment by akx** [comment]
Hello!

The mapping file is parsed using [`RawConfigParser`](https://docs.python.org/3/library/configparser.html). Unfortunately, it always strips leading and trailing whitespace:
> Leading and trailing whitespace is removed from keys and values.

If you are using Babel programmatically, though, you can pass in the mapping as a Python dictionary instead.

**Comment by djtm** [comment]
ok thanks, had to use other variables in the end
