### ISSUE TITLE
Locale.parse('und_HT') => UnknownLocaleError

### ISSUE THREAD

**Issue by achiang** [python-babel/babel#497]
Using babel 2.4.0, I am encountering an error when trying to detect the locale for Haiti.

```
In [1]: import babel

In [2]: babel.Locale.parse("und_HT")
---------------------------------------------------------------------------
UnknownLocaleError                        Traceback (most recent call last)
<ipython-input-2-b87273365c68> in <module>()
----> 1 babel.Locale.parse("und_HT")

/home/vagrant/local/venv/local/lib/python2.7/site-packages/babel/core.pyc in parse(cls, identifier, sep, resolve_likely_subtags)
    328                 return locale
    329 
--> 330         raise UnknownLocaleError(input_id)
    331 
    332     def __eq__(self, other):

UnknownLocaleError: unknown locale 'und_HT'
```

It does seem partially known though:

```
In [3]: babel.Locale.parse("fr_HT")
Out[3]: Locale('fr', territory='HT')
```

Here's the link in CLDR 28 - http://www.unicode.org/repos/cldr/tags/release-28/common/main/fr_HT.xml

Is this a misunderstanding on my part, of what `Local.parse()` is supposed to do, when given the `und_` prefix? Or is this an actual issue?

Thanks for clarification.

**Comment by akx** [comment]
Hi!

So, `und_FI` and `und_UK` do what they're supposed to (`fi_FI` and `en_GB` respectively), so `und_` basically works. However, it looks like the CLDR's "likely subtags" mapping maps `ht` to `ht_Latn_HT`, which is a locale the CLDR itself doesn't have anyway.

So basically, if you want `fr_HT`, you'll have to ask for it by hand, or maybe consult `babel.languages.get_official_languages()` and try one that fits:

```python
>>> import babel.languages
>>> babel.languages.get_official_languages('HT')
('ht', 'fr')
```

**Comment by jeancochrane** [comment]
@akx Sorry to bump this old thread but I figured you may know the answer -- do you know why `ht` isn't supported as a locale? I'm a little bit out of my depth reading the CLDR data, but it looks from the [likely subtags table](https://unicode-org.github.io/cldr-staging/charts/38/supplemental/likely_subtags.html) like `ht` is a supported source ID for Haitian Creole, so I'm confused why the following parse fails:

```
In [6]: Locale.parse('ht')
---------------------------------------------------------------------------
UnknownLocaleError                        Traceback (most recent call last)
<ipython-input-6-b51394ebf382> in <module>
----> 1 Locale.parse('ht')

~/.virtualenvs/remit-srv/lib/python3.8/site-packages/babel/core.py in parse(cls, identifier, sep, resolve_likely_subtags)
    329                 return locale
    330
--> 331         raise UnknownLocaleError(input_id)
    332
    333     def __eq__(self, other):
```
