### ISSUE TITLE
format_skeleton function and 'EEEE' pattern

### ISSUE THREAD

**Issue by vpassama** [python-babel/babel#499]
Hi,

I was just wondering why the 'EEEE' pattern explained [here](http://babel.pocoo.org/en/latest/dates.html#date-fields) doesn't work in the function [format_skeleton](http://babel.pocoo.org/en/stable/api/dates.html#babel.dates.format_skeleton).

I'm using babel 2.4.0 and I tried in a python console : 

```
from babel import dates

dates.format_skeleton('yMMMEEEdd', locale='en_US')
u'Mon, May 29, 2017'
dates.format_skeleton('yMMMEEEEdd', locale='en_US')
u'Mon, May 29, 2017'
```

It works as expected with format_date function : 

```
dates.format_date(locale='en_US', format='y MMM EEE dd')
u'2017 May Mon 29'
dates.format_date(locale='en_US', format='y MMM EEEE dd')
u'2017 May Monday 29'
```

Is it a bug or did I miss something ?

**Comment by adityahase** [comment]
Hi, 

I am new to babel, just to give my two cents, I took a brief look at [`format_date`](https://github.com/python-babel/babel/blob/master/babel/dates.py#L671-L701) and [`format_skeletons`](https://github.com/python-babel/babel/blob/master/babel/dates.py#L805-L840).

It seems neither `yMMMEEEdd` nor `yMMMEEEEdd` are available as skeletons for `locale='en_US'`, (you can get available skeletons from `Locale('en_US').datetime_skeletons`), so as mentioned in [docs](http://babel.pocoo.org/en/stable/api/dates.html#babel.dates.format_skeleton) both of them are mapped to closest match available according to rules outlined in [TR35 document](http://unicode.org/reports/tr35/tr35-dates.html#Matching_Skeletons) using [`dates.match_skeleton`](https://github.com/python-babel/babel/blob/master/babel/dates.py#L1706-L1773), i.e. to `yMMMEd` which corresponds to `<DateTimePattern 'E, MMM d, y'>`, hence the result.

This behavior is clearly documented, I guess it isn't a bug.

**Comment by vpassama** [comment]
Ok, thank you for the answer !
