### ISSUE TITLE
Test fails randomly

### ISSUE THREAD

**Issue by benselme** [python-babel/babel#507]
`CommandLineInterfaceTestCase.test_extract_with_mapping_file` fails randomly because it uses `datetime.now`. It should use a fixed date/time.

**Comment by narendravardi** [comment]
@benselme can i work on this?

**Comment by benselme** [comment]
Sure why not ? Go ahead !

**Comment by prabhath6** [comment]
@benselme I looked into this and the only approach I could find is to modify parameters specified to the command line interface `extract` to include `creation_date` as an option. Creation_date can be passed into run function and then pass  creation_data into Catalog creation. This way we can insert required date into the .pot file creation.

**Comment by benselme** [comment]
What's needed is just to replace the calls to `now` with a constant, abitrary `datetime`. Nothing more. It's really an easy one !

**Comment by narendravardi** [comment]
@benselme, Why is only `test_extract_with_mapping_file` unit test is failing?

datetime logic looks similar for all unit tests. Please give me some time to verify and let me come back to you.

**Comment by benselme** [comment]
I saw this one fail the other day. That doesn't mean others couldn't fail for the same reason. No test should be using `datetime.now`.

**Comment by bagxi** [comment]
If i truly understand all occurrences of 'datetile.now' in 'test_frontend.py'
 should be replaced with e.g. 'datetime(1970, 1, 1, 00, 00)' ?
If true i'll open pull request.

**Comment by narendravardi** [comment]
@benselme, I am trying to search where `temp.pot` is being initialized but no luck. Can you please help me out?

**Comment by benselme** [comment]
`ExtractMessagesTestCase.setUp` creates an instance of `frontend.extract_messages` and then `run`s it in various tests. `run` creates the `temp.pot` file.

**Comment by narendravardi** [comment]
@benselme as @prabhath6 suggested, we have to make changes to include additional parameters. If we change `datetime.now` in testcases to some constant value, the testcases will keep failing.

See the travis build for that change: https://travis-ci.org/narendravardi/babel/jobs/251038270

The `actual_content` will be dynamic and uses `datetime.now` and  `expected_content` is constant.

Please let me know if you an any other ideas :)

**Comment by akx** [comment]
I've successfully used the [`freezegun`](https://github.com/spulec/freezegun) library to, well, freeze time during tests. That might work.

**Comment by benselme** [comment]
`mock` can do that as well and is included with python starting with 2.7.

Or maybe we should allow the arbitrary setting of `PO-Revision-Date`  (see #503). But that's a different project altogether.

**Comment by narendravardi** [comment]
@benselme @akx If it's not urgent. Please give me some time, I will update you with the fix.

**Comment by narendravardi** [comment]
@benselme @akx I have used [freezegun](https://github.com/spulec/freezegun) library to freeze the time while running the tests in the `tests/messages/test_frontend.py`. 

Requesting you to review the changes.
