### ISSUE TITLE
Travis-CI rejects all new jobs

### ISSUE THREAD

**Issue by benselme** [python-babel/babel#509]
So I filed an issue with travis-ci because we're not able to merge anything anymore:
https://github.com/travis-ci/travis-ci/issues/7974

Here's the answer I got:
"Someone appears to have set the maximum number of concurrent builds for this repository to 0, effectively disabling Travis CI. An admin should raise the limit. I think the builds should start without further intervention, but if they do not, try closing and reopening the affected PRs."

Admins, we need your help !

@akx @sils @etanol  @python-babel/babel-admins

**Comment by akx** [comment]
The setting for maximum concurrent builds was 5 according to the UI, but I've disabled limiting maximum concurrent builds at all.
FWIW, I can't recall fiddling with the setting before, so not sure what happened.

Anyway, oughta be good now!

**Comment by benselme** [comment]
Thanks !

But alas, no it still isn't good. We're still trying to work things out with someone from travis in the aforementioned issue. I'll post updates here when I have any.

**Comment by benselme** [comment]
So it's been nearly one month that we can't merge anything. The travis people have acknowledged that there is a problem on their side but haven't fixed it for now.

@akx I think we should make travis-ci non mandatory for merging so we can move forward.

**Comment by akx** [comment]
This flew under my radar, sorry. You're right – I've disabled the requirement for Travis for now. (I would've done it earlier, but I didn't think I had the privileges for that...)
