### ISSUE TITLE
Need a release with an already merged fix on Python3 in

### ISSUE THREAD

**Issue by zxyviopond** [python-babel/babel#516]
Hello, the python3 issue before caused our development issue and luckily I already see a fix in https://github.com/python-babel/babel/commit/be718f3a7b2b71e936dcc3b498b7013537aa9036

To unblock our work, we need a release that include the above fix. Hope that can happen soon, Thank you.

**Comment by jtschoonhoven** [comment]
+1

**Comment by akx** [comment]
I'm preparing a release now. Sorry for the wait!

**Comment by akx** [comment]
Version 2.5.0 has been released:

* https://github.com/python-babel/babel/releases/tag/v2.5.0
* https://pypi.org/project/Babel/
