### ISSUE TITLE
pybabel update fuzzy algorithm is not the same as msgmerge

### ISSUE THREAD

**Issue by ghost** [python-babel/babel#524]
The msgmerge gettext algorithm to find and mark fuzzy translations will find that, for instance, replacing a trailing exclamation point with a trailing dot is *fuzzy*.

<pre>
#: journalist.py:308
#, fuzzy
msgid "Account updated."
msgstr "Le compte a été mis à jour avec succès !"
</pre>

The **pybabel update** function uses [a different algorithm](https://github.com/python-babel/babel/blob/master/babel/messages/catalog.py#L780) which leads to significantly different outcomes.

I will revert to using msgmerge because I prefer the fuzzy algorithm it has. It would be good if this significant difference is documented in the help of **pybabel update**. Or even better, if the user could chose between the two algorithm.

What do you think ?

**Comment by akx** [comment]
Sure, an option for choosing between fuzziness algorithms would be fine by me.

In case you're interested in writing a PR that implements the `msgmerge` fuzziness algorithm in Python, the C sources seem to be [this fragment in `msgmerge`](https://github.com/autotools-mirror/gettext/blob/5ad8c92742daaf4434fded196ff23638cdaa621b/gettext-tools/src/msgmerge.c#L825-L883), which has historically (before https://github.com/autotools-mirror/gettext/commit/101de35be7c8e73329d8801f9eca938690130cb1 in 2008) used [this fuzzy-search implementation](https://github.com/autotools-mirror/gettext/blob/5ad8c92742daaf4434fded196ff23638cdaa621b/gettext-tools/src/message.c#L560-L634) but uses [this hash-based implementation](https://github.com/autotools-mirror/gettext/blob/5ad8c92742daaf4434fded196ff23638cdaa621b/gettext-tools/src/msgl-fsearch.c) these days. (I have no idea whether the old and new implementations differ in results – sorry!)

The "meat" of Gettext's fuzziness function, `fstrcmp_bounded`, can be found [here in `gnulib`](https://github.com/coreutils/gnulib/blob/ca35d468121a7ec60162155f9c3395068ca323d1/lib/fstrcmp.c#L85). I believe it's an implementation of the Levenshtein algorithm for edit distance, while `difflib.get_close_matches()`, which Babel uses, is [something quite different](https://github.com/python/cpython/blob/b157ce1e58b03988ce4340a55d0b856125833cc5/Lib/difflib.py#L43).

Hope that helps.

**Comment by dachary** [comment]
> Sure, an option for choosing between fuzziness algorithms would be fine by me.

To be completely honest I don't have the fuel to do that myself right now. I hope some enthusiastic volunteer with a lot of spare time will discover this discussion and do some magic :-)
