### ISSUE TITLE
messages not extracted from folders starting with _ or .

### ISSUE THREAD

**Issue by mrtopf** [python-babel/babel#53]
Unfortunately I have folders like _m containing templates I would like to be translated. Right now pybabel is ignoring those. I can patch this but was wondering if there is a known reason for this before doing so.

**Comment by andrewdiamond** [comment]
Also have same problem with ".../_include/.." subfolder

**Comment by slimakovec** [comment]
why isn't the branch still merged? And most importantly - why this issue exist after 3 years?!

**Comment by sils1297** [comment]
@slimakovec I can't find a PR associated with that commit apart from it being incomplete as mentioned in the commit message.

Babel was unmaintained for a long time. This time is more or less over and Babel does receive light maintaining from a few people now, we're sorry that so many issues still exist but time is a precious resource. We are happy to accept and review pull requests that solve this issue, maybe based on that existing commit? (In that case please don't forget to attribute at least to the original author.)

**Comment by sudheesh001** [comment]
@nandoflorestan Your code seems like a great headstart for me as a new contributor to babel to pick and solve. I will give this a shot and try to fix this.

**Comment by nandoflorestan** [comment]
@sudheesh001 that's great news, thanks!

**Comment by samilyak** [comment]
It's 2018 already and nobody touched this?? :)
This is probably the issue that's every single user of babel faced with immediately after incorporating it in his project.

@akx suggestion here https://github.com/python-babel/babel/issues/402 sounds most reasonable to me.

Is anybody up to fix this ridiculous issue already?

Removing `subdir.startswith('_')` at https://github.com/python-babel/babel/blob/master/babel/messages/extract.py#L142 at least and release it to pip is not a big deal IMO.

**Comment by jun66j5** [comment]
-1 before fixing #402. I'm using this behavior to avoid traversing directories with many entries (e.g. node_modules).

**Comment by Lohiths0** [comment]
Hello, I'm new to open source contribution and I want to try to attempt at solving this issue. Is this issue still open?

**Comment by priyansh19** [comment]
Hello, I'm new to open source and I want to contribute to solving this issue of pybabel. Is this issue still open for contribution?

**Comment by azzamsa** [comment]
Any workaround for now?

It has been 7 years.

My current hack is just to write them manually,

**Comment by shub-garg** [comment]
Hello, if this issue is open I would like to work on it.

**Comment by pranavkhekare** [comment]
Hello,
Is this issue still open?

**Comment by Amaimersion** [comment]
Bump

**Comment by Amaimersion** [comment]
Here is simple workaround:

1) Most probably you don't need to change your `babel.cfg`

2) From now run `pybabel` from Python script, not from Terminal:

```python
# file: pybabel.py

import os

messages_file = "messages.pot"
extract_command = (
    "pybabel extract -F babel.cfg -k lazy_gettext "
    f"-o {messages_file} ."
)

if os.system(extract_command):
    # error
    return
```

```shell
python3 pybabel.py
```

3) Add all inputs paths manually instead of dot symbol:

```python
# file: pybabel.py

import os
import glob

messages_file = "messages.pot"
files_to_translate = " ".join([
    # assuming that you run this script from project root
    *glob.glob("src/**/*.py", recursive=True),
    *glob.glob("src/**/*.html", recursive=True)
])
extract_command = (
    "pybabel extract -F babel.cfg -k lazy_gettext "
    f"-o {messages_file} {files_to_translate}"
)

if os.system(extract_command):
    # error
    return
```

4) Filter yours `files_to_translate` as needed
