### ISSUE TITLE
pip install bable 2.5.1 failed

### ISSUE THREAD

**Issue by alanpurple** [python-babel/babel#535]
windows 10 x64
python 3.6.2 ( included in Anaconda 5.0.0 x64 )

Collecting babel==2.5.1
  Using cached Babel-2.5.1-py2.py3-none-any.whl
Requirement already satisfied: pytz>=0a in c:\anaconda3\lib\site-packages (from babel==2.5.1)
Installing collected packages: babel
  Found existing installation: babel 2.5.0
Cannot remove entries from nonexistent file c:\anaconda3\lib\site-packages\easy-install.pth
----- Failed to install 'babel' -----

**Comment by akx** [comment]
This doesn't seem to be a Babel problem, but something to do with your previous installation of Babel 2.5.0, which `pip` is trying to first uninstall.

Maybe look for traces of Babel in your `c:\anaconda3\lib\site-packages` directory and clean them first.

**Comment by alanpurple** [comment]
@akx 
deleting Babel-2.5.0-py3.6.egg folder resolve this, thanks
