### ISSUE TITLE
Locale’s display names not capitalized?

### ISSUE THREAD

**Issue by jenstroeger** [python-babel/babel#544]
I just stumbled upon a curious detail:
```python
>>> import babel
>>> babel.__version__
'2.5.0'
>>> en = babel.Locale("en")
>>> en.display_name
'English'
>>> pt = babel.Locale("pt")
>>> pt.get_display_name()
'português'
>>> pt.get_display_name(en)
'Portuguese'
```
It seems that some locales have a native lower-case [display name](http://babel.pocoo.org/en/latest/locale.html#locale-display-names), and others (e.g. `"English"`, `"Deutsch"`) don’t. Is that intended, and why?

**Comment by akx** [comment]
I think this is intended. English is "English" in English, no matter where in the sentence it is, and for instance my native Finnish separates between Suomi (the country of Finland) and suomi (the language) by case alone. :)

**Comment by jenstroeger** [comment]
@akx, thanks! So [Wikipedia](https://www.wikipedia.org/) gets its list of supported languages wrong then?

**Comment by akx** [comment]
I'd consider those titles, not just nouns, so they are written in [Title Case (or Title case, depending on language)](https://en.wikipedia.org/wiki/Letter_case#Title_case). So no, not really wrong, I'd say.

**Comment by jenstroeger** [comment]
Fairnuff. Ok, closing this issue and I trust that Babel does the right thing… 🤓
