### ISSUE TITLE
Allow some form of Babel supplied locales if not supplied by CLDR

### ISSUE THREAD

**Issue by icarito** [python-babel/babel#55]
From http://babel.edgewall.org/ticket/258:
"If CLDR does not provide some locale, e.g. Asturian (#254), then we should provide a mechanism that allows the locale identifier to be used as well as to be overriden with user data to support said locale."

In my case, I'm trying to add support for Aymara, which locales were recently submitted to GLIBC for inclusion ( http://sourceware.org/bugzilla/show_bug.cgi?id=14828 ) . Now I'm dumbfounded by learning that Babel doesn't use the glibc locales but something else called CLDR.

It would be great if I could simply use the glibc localedata.

**Comment by etanol** [comment]
Indeed, the right approach for supporting new locales or updating existing ones is to contribute directly to CLDR.  This way the effort is concentrated since many more libraries and frameworks depend on it.

**Comment by srl295** [comment]
if anything, given the above, you could write your files in CLDR format (which you should anyways to contribute to CLDR) and then run the import manually.

**Comment by etanol** [comment]
@srl295 that wouldn't work.  The CLDR data is imported at *release time*.  That is, as part of the packaging process, the XML files are parsed and a custom serialized format is generated for each locale, so Babel loads locale data faster and in a native way.

API compatibility is maintained as much as possible.  However, the exact format of the babel data files is opaque and not formally defined.  This means that the exchange of locale data files across different Babel versions is **not** supported.
