### ISSUE TITLE
Release 2.5.2 is not backward compatible

### ISSUE THREAD

**Issue by chessbr** [python-babel/babel#550]
The last release includes this commit https://github.com/python-babel/babel/commit/cf03578b117f92f0af23ae07a65c3e2eada5c30c which changes the NumberPattern.apply signature from

```py
def apply(self, value, locale, currency=None, force_frac=None):
```
to
```py
def apply(self, value, locale, currency=None, currency_digits=True):
```
chopping out the `force_frac` param.

Is this project following semver? Our build started to break on version 2.x. If this is not the case I can just fix the version on our project for now until we update the project.

Thanks

**Comment by chessbr** [comment]
No problem @akx !
Thank you for the support!

**Comment by akx** [comment]
Version 2.5.3, which is v2.5.1 + 7cedb84, 29da2d2, and edfb518, has been pushed to PyPI.

Once again, sorry about the screw-up! 😥
