### ISSUE TITLE
[Missing support] Occitan language

### ISSUE THREAD

**Issue by Quenty31** [python-babel/babel#553]
I'm writting this issue for the Occitan language, spoken in South France, Spain, Italy and Monaco, is not supported yet.
Its code is OC.
It's included in the CDLR: http://www.unicode.org/cldr/charts/32/supplemental/locale_coverage.html
Best regards

**Comment by akx** [comment]
Hi @Quenty31, and thanks for reaching out. :) 

First off, I'd love to know what you're planning to use the `oc` locale for, as that kind of dictates what we should do with the issue. I mean, as it is, we're only including data from the _common_ status set of locales in the CLDR, and it looks like, according to the linked page, that Occitan is currently in _seed_ ("_seed_ — preliminary locales that do not yet have sufficient vetted data" ([1])).

That said, it might actually be a good idea (a slightly political choice, I suppose), to also include whatever we can from the _seed_ set, but mark the locales as such, i.e. something like `babel.locale('oc').status == 'seed'`.

[1]: http://cldr.unicode.org/index/downloads#Repository_Organization

**Comment by Quenty31** [comment]
It's for the searx project: https://github.com/asciimoo/searx/issues/1143
I had no problem to translate Mastodon, diaspora* or Firefox.
