### ISSUE TITLE
Unknown locale 'de_IT'

### ISSUE THREAD

**Issue by voidus** [python-babel/babel#568]
Hello :wave: 
I'm trying to add German (Italy) to my project, but babel doesn't recognize 'de_IT'.

I tried to find out if it is included in cldr, but I couldn't find the place to look :neutral_face: 

German is an official language in parts of Italy[1], so 'de_IT' should be included if I'm not mistaken.

[1] " Today both German and Italian have the status of co-official languages in South Tyrol." from https://en.wikipedia.org/wiki/Trentino-Alto_Adige/S%C3%BCdtirol#Languages

**Comment by akx** [comment]
Hi!

It looks like support for `de_IT` is added in CLDR 32. CLDR 32 is used by the current development `master` version of Babel, but that code hasn't been released yet.

Unfortunately I have no idea as to when the next version will be released 😞

**Comment by voidus** [comment]
I guess I'll just have to wait and see.
Thank  you for the swift feedback :)

**Comment by MythicManiac** [comment]
**Slightly relevant question:**
Would it make sense at all to allow ignoring the locale whitelist via a flag of some kind, or is there something practically preventing it (beyond larger support surface)? It could prove useful in cases like these, or if someone insists on using non-standard locales.

**Comment by akx** [comment]
@MythicManiac - There are two sides to Babel: the CLDR-based formatting stuff, and the message catalog bits (which only really use CLDR data to figure out the different plural rules for different languages). The PR #557 (not merged yet) makes Babel less strict in the latter case, so one can manage message catalogs that are in locales unknown to Babel, but to instantiate a Locale object, it still has to be a known locale.

@voidus - Speaking of which, which are you doing with `de_IT`? Messages or something else? :)

**Comment by voidus** [comment]
I need the IT-Part to present different content based on the country.

**Comment by akx** [comment]
[Babel 2.6.0](https://github.com/python-babel/babel/releases/tag/v2.6.0) uses CLDR 33, so this should now work. :)
