### ISSUE TITLE
Implement currency formatting with long display names. 

### ISSUE THREAD

**Issue by spookylukey** [python-babel/babel#578]
Namely, things like:

    "123,456.78 US dollars"

(en locale)

or

    "dólares estadounidenses 123,456.78"

(es-GT locale)

The algorithm for doing this is described here: https://www.unicode.org/reports/tr35/tr35-numbers.html#Currencies and CLDR contains the data.

I'd be happy to attempt to implement this myself. Two issues I'm aware of:

1) What should the API be? An extra parameter to `format_currency`? A new `format_type` (this risks clashing with other format types already defined)?

2) It looks like this would require data not currently available in the pickled locale data. Specifically it requires the `unitPattern` data. I'm not sure how to go about adding this - apart from the `import_cldr.py` script, is there a specific process to follow?

For comparison, browsers currently implement this as part of [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) using options `{currencyDisplay: "name"}`. In a browser console you can do:

    > Intl.NumberFormat("en", {currencyDisplay:"name", style:"currency", currency:"USD"}).format(123456.78)
    "123,456.78 US dollars"

**Comment by akx** [comment]
Heya! Yeah, this sounds like a good addition :)

Regarding locale data, there's no specific process. Just use common sense when coming up with the key within `data` to load the new data into – `currency_unit_patterns` sounds good, for instance.

API-wise, taking a cue from the JavaScript API, maybe `format_type="name"` would be a sane option? I don't think that'll end up clashing with any of the current formats (which seem to be `standard`, `standard:short` and `accounting`).

**Comment by spookylukey** [comment]
@akx - thanks so much for the reply. I'm not sure when I'll actually get round to this, but wanted to get things lined up for when I do have the time!
