### ISSUE TITLE
The `parse_decimal` function accepts irregular input

### ISSUE THREAD

**Issue by Changaco** [python-babel/babel#589]
Examples:

```python
>>> parse_decimal('1,,000', locale='en_US')
1000
>>> parse_decimal('25.00', locale='de')
2500
```

Inputting `25.00` instead of `25,00` is an easy mistake to make, and it can be confusing that the software reads it as `2500` instead of `25`.

Maybe `parse_decimal` should be more strict and reject numbers formatted in a weird way?

This would require checking that the separators are positioned correctly before [replacing them](https://github.com/python-babel/babel/blob/v2.6.0/babel/numbers.py#L604-L605).

**Comment by akx** [comment]
Good idea. If you're feeling up for implementing this, just make sure strictness is optional, i.e. a new `strict=False` flag for the function.
