### ISSUE TITLE
format_date(locale='pl') returns different string than angularJS

### ISSUE THREAD

**Issue by miroslavrehor** [python-babel/babel#591]
# Overview Description
Polish format date medium returns different date format than angularJS.

# Steps to Reproduce
babel: format_date(date(2017, 4, 7), format='medium', locale='pl')
angularJS: {{1175414401000 | date:'mediumDate' }}

# Actual Results
babel: 1 kwi 2007
angularJS: 01.04.2007

# Expected Results
Babel same as angularJS

# Additional Information:
The issue might be on angularJS side. But based on my tests below it seems babel might be wrong.

![image](https://user-images.githubusercontent.com/1447944/41512547-3732965a-728a-11e8-8b22-33e85ebb7880.png)

**Comment by akx** [comment]
Hi!

According to https://www.unicode.org/cldr/charts/33/summary/pl.html#2237 the `medium` date format for Polish is `d MMM y G` in the current Unicode CLDR version, which is the data Babel uses. (According to the [blame](https://unicode.org/cldr/trac/browser/trunk/common/main/pl.xml?annotate=blame#L1661) it has been like this for 5 years.)

`MMM` [maps to](https://github.com/python-babel/babel/blob/master/babel/dates.py#L1341-L1342) the abbreviated month name, [which is `kwi`](https://www.unicode.org/cldr/charts/33/summary/pl.html?hide#1952) in the data.

That is to say, Babel seems to be acting according to the CLDR version it is using. 

If you feel the CLDR has wrong data, you can open a ticket over at their tracker, or contribute using their survey tool.
