### ISSUE TITLE
Local Packages missing on install

### ISSUE THREAD

**Issue by amracel** [python-babel/babel#593]
Trying to install 2.6.0-py36_0 using conda and receiving the following errors:

The following NEW packages will be INSTALLED:

    babel: 2.6.0-py36_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/global.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/af.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/am.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ar.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/as.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ast.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/az.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/be.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/bg.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/bn.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/br.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/brx.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/bs.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/bs_Cyrl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ca.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ccp.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ce.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/chr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/cs.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/cy.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/da.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/de.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/dsb.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/dz.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ee.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/el.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/en.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/es.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/et.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/eu.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fa.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fi.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fil.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fo.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/fy.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ga.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/gd.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/gl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/gsw.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/gu.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/he.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/hi.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/hr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/hsb.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/hu.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/hy.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/id.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/is.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/it.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ja.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ka.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/kab.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/kk.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/km.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/kn.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ko.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ks.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ksh.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ky.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/lb.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/lo.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/lt.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/lv.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/mk.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ml.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/mn.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/mr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ms.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/mt.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/my.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/nb.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ne.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/nl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/nn.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/or.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/pa.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/pl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ps.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/pt.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ro.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ru.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sd.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/si.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sk.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sq.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sr_Latn.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sv.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/sw.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ta.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/te.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/th.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/tk.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/to.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/tr.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ug.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/uk.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/ur.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/uz.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/uz_Cyrl.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/vi.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/yue.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/yue_Hans.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/zh.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/zh_Hant.dat'
specified in the package manifest cannot be found.

CondaVerificationError: The package for babel located at C:\Development\Anaconda35\pkgs\babel-2.6.0-py36_0
appears to be corrupted. The path 'Lib/site-packages/babel/locale-data/zu.dat'
specified in the package manifest cannot be found.

I had an earlier version installed and tried an update first with the same results. The above appeared when I tried uninstalling and reinstalling.

**Comment by amracel** [comment]
I finally ended up zipping up this project and unzipping it, replacing what I had. That seemed to work to get spyder working, which was my ultimate goal.

**Comment by akx** [comment]
I'm not at all familiar with Anaconda, but I'm glad you got it working somehow! :)

Closing for housekeeping purposes.
