### ISSUE TITLE
Please add currency symbol "Rp." for "IDR" in babel.numbers.format_currency

### ISSUE THREAD

**Issue by allealdine** [python-babel/babel#595]
At the moment, if we do:

```python
from babel.numbers import format_currency as fc
print (fc(123.0,"USD"))
print (fc(123.0,"JPY"))
print (fc(123.0,"IDR"))
```
will get
```python
$123.00
¥123
IDR123
```
it should be:
```python
$123.00
¥123
Rp.123
```

**Comment by akx** [comment]
Hi!

All currency symbol data in Babel comes from the Unicode CLDR.

You can propose changes and additions such as this using the [CLDR Survey Tool](http://cldr.unicode.org/index/survey-tool).

**Comment by akx** [comment]
Closing as unrelated to Babel itself.

For the record, though, at least as of CLDR 35.1 (as of yet unreleased), IDRs are formatted as Rp in the `id` locale:

```python
>>> from babel.numbers import format_currency as fc
>>> print(fc(123.0, "IDR"))
IDR123.00
>>> print(fc(123.0, "IDR", locale='id'))
Rp123,00
```
