### ISSUE TITLE
Repeated suggestions in parse_decimal strict mode 

### ISSUE THREAD

**Issue by jorgesumle** [python-babel/babel#596]
When you enter 0.00 in languages which use commas for delimiters using the strict mode of `parse_decimal`, you get two times the same suggestion.

<pre><samp>babel.numbers.NumberFormatError: '0.00' is not a properly formatted decimal number. Did you mean '0'? Or maybe '0'?</samp></pre>

Related to [issue 1177](https://github.com/liberapay/liberapay.com/issues/1177) of Liberapay.

**Comment by akx** [comment]
Care to write a PR? The fix is easy :)

**Comment by fuzzmz** [comment]
Is this case only for `0.00` or for any `x.00`?
