### ISSUE TITLE
I believe the underlying language data is incorrect

### ISSUE THREAD

**Issue by dmckinno** [python-babel/babel#598]
I wanted to build a dictionary mapping country names to languages spoken there. Babel's database is right for the majority of countries, but assigned English to a number of European countries (Belgium for instance) for which English is not the official language.

I used the code below.

```python
country = []
language = []
for locale in list_of_locales:
    l = Locale.parse(locale)
    country.append(l.territory_name)
    language.append(l.language_name)
```

**Comment by akx** [comment]
Hi!

There may be locale combinations that don't correspond to official languages, so that's not the correct way to go about this.

Instead, please use the [`babel.languages.get_official_languages()`](http://babel.pocoo.org/en/latest/api/languages.html#babel.languages.get_official_languages) API.
