### ISSUE TITLE
Getting 500 error on babel 

### ISSUE THREAD

**Issue by splnanthakumar** [python-babel/babel#602]
ActualLine of Code where the exception raise:
resp_dict = {"message": gettext("Deleted Successfully"), "status_code": 204}

Error:
external_api.py:608 'babel'
validator.py:243 'CG ERROR: My Exception  : babel , Error code :500'

Babel version : 2.6.0

i am getting this error when i make request from api gateway .

**Comment by akx** [comment]
Hello!
It's hard to tell exactly what is going on from those lines. Can you get a traceback out?

**Comment by splnanthakumar** [comment]
thanks. i got the issue. babel selector was not registered that was the problem.
