### ISSUE TITLE
unorderable types in write_po

### ISSUE THREAD

**Issue by mfrasca** [python-babel/babel#606]
I'm using babel-2.6.0, and I'm hitting a problem with generated data, not something I can fix on that end.

I have a standard Makefile for generating `pot` files, then I use `msgcat` to produce a single merged pot, which I then update with the line:
```
sphinx-intl update -p _build/locale-merged $(for i in $LANGUAGES; do printf -- '-l %s ' $i; done)
```

and the result is a crash:
```
babel/messages/pofile.py", line 552, in write_po
    for filename, lineno in sorted(message.locations):
TypeError: unorderable types: NoneType() < int()
```

which I fixed very brutally by adding a `key` parameter to the `sorted` function:
```
sorted(message.locations, key=(lambda x: (x[0], x[1] or -1)))
```

**Comment by Timtam** [comment]
Same here, when feeding a catalog via
cat.add(
        'some translatable string',
        locations = ('/some/path/to/some/file',
                     20,
                    ),
        ...
    )

write_po() will always fail due to the attempt of sorting strings and integers in one go.
Will probably have to find an older version which doesn't run into this issue now until you get it fixed.
Best Regards.
Timtam

**Comment by mfrasca** [comment]
I'm curious: why the try-except block (giving up on any ordering) instead of a partial ordering function as the approach in my report?

**Comment by akx** [comment]
@mfrasca My reasoning was that it could _also_ fail, but come to think of it, I could have made the `try:except:`'d `sorted` statement use that key function. If you feel like making a PR for it, we can ship it in 2.7.1 or something :)
