### ISSUE TITLE
Python 3.7 warnings

### ISSUE THREAD

**Issue by tirkarthi** [python-babel/babel#607]
Python 3.7 introduced a warning with respect to collections that will be removed in 3.8 making the project incompatible with 3.8.

Found at https://travis-ci.org/python/cpython/jobs/446051148#L2596

> /home/travis/build/python/cpython/Doc/venv/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py:3226: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Sample fix : https://github.com/pallets/markupsafe/pull/98

**Comment by akx** [comment]
The warning seems to originate from `pkg_resources`'s vendored version of `pyparsing`.
`pkg_resources` is not a dependency of Babel's, so this is probably not a Babel bug.

Closing, but please let me know if I'm wrong!

**Comment by tirkarthi** [comment]
Sorry, my bad I copy pasted the wrong line for reference. Please find the actual warning as below. I checked master and the line is still present so the warning is valid. I would request reopening this.

> /home/travis/build/python/cpython/Doc/venv/lib/python3.8/site-packages/babel/localedata.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by akx** [comment]
Ah, that's more like it then. Reopening :)

**Comment by tirkarthi** [comment]
I guess it's the only place. I grep for similar places if any and raise a PR. Also adding 3.7 to Travis might help which I can add as part of the same PR if it's ok.

**Comment by akx** [comment]
Please do! :)

**Comment by tirkarthi** [comment]
Fixed with https://github.com/python-babel/babel/pull/609 closing.
