### ISSUE TITLE
Weeknumber wrong for 2018-12-31

### ISSUE THREAD

**Issue by BT-sschmid** [python-babel/babel#619]
As mentioned in the docs babel.dates.format_date uses the ISO-Calendar when passing "YYYY" as format string.

Evaluating gives
```
babel.dates.format_date(datetime.datetime(2018,12,31
                                         ), format="w YYYY", locale='en_US')
>> u'53 2018'
```
The correct result should be 1 2019 by iso definitions.

Thanks for your reply

**Comment by alexander-heyber-manatec** [comment]
Are there any news about this bug? Since Babel is used in Odoo, the weeknumber bug is present there and should be fixed soon.

**Comment by Julien00859** [comment]
@alexander-heyber-manatec 

> Are there any news about this bug? Since Babel is used in Odoo, the weeknumber bug is present there and should be fixed soon.

Odoo uses a previous version of babel (namely the 2.3.4) we do not update dependencies on stable version. Hopefully this fix will be part of a coming babel release and be part of the next Odoo stable version (namely v13).
