### ISSUE TITLE
Norwegian language return wrong code

### ISSUE THREAD

**Issue by marcusolofsson** [python-babel/babel#623]
# Overview Description
The language code returned by is wrong for Norwegian.

# Steps to Reproduce

1. `pip install babel==2.6.0`
2. `import babel`
3. `babel.Locale.parse('no').language`
4. `babel.Locale.parse('nor').language`
# Actual Results
`nb`
`nb`

# Expected Results
`no`
`no`

# Additional Information:

they should be `no`
according to [Norwegian codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
to get nb you should need to be explicit and say either `nb` or `nob`

# system info
- `uname --all`
Linux station36 4.18.0-12-generic #13-Ubuntu SMP Wed Nov 14 15:17:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- `python --version`
Python 2.7.15+

- `pip list`
Package                            Version                 
---------------------------------- ------------------------
....                  
Babel                              2.6.0                   
....

**Comment by akx** [comment]
The macrolanguage "Norwegian" is not really supported as far as I know – you can either get Norwegian Bokmål or Norwegian Nynorsk.
