### ISSUE TITLE
The en_GB (British English) locale's first week day is incorrect.

### ISSUE THREAD

**Issue by andyewen** [python-babel/babel#624]
According to the [CLDR](http://www.unicode.org/cldr/charts/29/supplemental/territory_information.html#GB), the UK's week starts on a Monday, with Sunday as a variant. However, python-babel returns `6` for the `first_week_day` property. I imagine this is a parsing bug where the correct value is being overwritten by a variant because the variant was parsed after the correct value.

**Comment by akx** [comment]
The linked information says the first day of the week is "mon, sun", whatever having two values means...

However, yeah, this is a bug!

In recent CLDR data, there is this:

```xml
<firstDay day="sun" territories="GB" alt="variant" references="Shorter Oxford Dictionary (5th edition, 2002)"/>
```

While most of the import code does ignore `alt="variant"`, the `firstDay` code import does not, and happens to read that as an override.
