### ISSUE TITLE
Python 3.8 compatible release?

### ISSUE THREAD

**Issue by JulienPalard** [python-babel/babel#641]
Hi Babel team!

From a cpython point of view I think it's time for a release just because https://github.com/python-babel/babel/pull/609 has been merged and it was the only one required for Python 3.8, so from this really small and precise point of view, a release would be appreciated.

Babel is a docs.python.org dependency and we're having a few warnings in our CI that could be fixed by a new release (see https://bugs.python.org/issue35293). Those warnings may upgrade to errors with the 3.8 release, having a babel release before could be great, but I understand it may not be trivial.

**Comment by akx** [comment]
I just released Babel 2.7.0, which is Python 3.8 compatible. 😄 🎉
