### ISSUE TITLE
Unknown reason causes "placeholders are incompatible"

### ISSUE THREAD

**Issue by Sraw** [python-babel/babel#655]
pybabel version: 2.7.0

When I use `pybabel compile -f -d dir` to compile a file, it throws an error:

    placeholders are incompatible

And the related texts are:

```
#: templates/source.jinja2:42
#, python-format
msgid ""
"Some original text"
"Some original text"
msgstr ""
"Some translation"
"Some translation"
```

But I don't know what is the problem?

**Comment by neulf** [comment]
me too.

**Comment by nexovec** [comment]
Were you able to resolve the issue?

**Comment by Soloknir** [comment]
@neulf  @nexovec Do you found something about this issue?

**Comment by zamentur** [comment]
On another project we had this with a percentage symbol % in msgid and msgstr
