### ISSUE TITLE
CLDR support / Months

### ISSUE THREAD

**Issue by Larsene** [python-babel/babel#663]
Hi, i've encountered a problem with babel format_skeleton...

[CLDR : Stand-Alone Month - Use one or two for the numerical month, three for the abbreviation, four for the full (wide) name, or 5 for the narrow name.](http://www.unicode.org/reports/tr35/tr35-45/tr35-dates.html#dfst-month)

```
from datetime import datetime
from babel.dates import format_skeleton
d = datetime.now()
print(format_skeleton('MMMM', d, locale = 'fr'))
```
should be 'septembre', and the value printed is 'sept.'

`
print(format_skeleton('MMMMM', d, locale = 'fr'))
`
should be 'S', and the value printed is 'sept.'

**Comment by TM2500** [comment]
Hi,
I don't want to be picky, but wouldn't it be easier to just use ```format_date()``` in the case  you just ant to localize a single field?

In your case that would be:
```
from datetime import datetime
from babel.dates import format_date

d = datetime.today()
print(format_date(d, 'MMMMM' ,locale='fr'))
```
This behaves exactly as specified in CLDR ;-)

I'm not a frequent user of this library but my understanding is that the ```format_skeleton()``` works best for combining different fields and then it also only produces values which are defined in the locale else it returns the nearest possible pattern.

**Comment by Larsene** [comment]
@TM2500 : right, but this is just an example. I wanted to use not only a single field, but a real date format. I'll change for format_date() and some concatenation...
