### ISSUE TITLE
Add Support for CLDR 24 Pluralization Rules

### ISSUE THREAD

**Issue by mitsuhiko** [python-babel/babel#67]
CLDR completely changed how it handles pluralization in 24.  The following big questions are raised by it:

- do we support old ones still?
- how is this supposed to work, why does german have an other rule now? Knock-on effects for users
- can we fudge the old behavior somehow?
- what are the changes of supporting decimal places for the API?

http://www.unicode.org/reports/tr35/tr35-numbers.html#Samples

**Comment by akx** [comment]
I think this issue is obsolete (or rather, already complete) since commits 546755f77b98a4ae4ddc29cb4c44b81cd88a31b1..e3bc00c7c3569046ac9ac1358de820738f7023db switched us to CLDR 24, then to 25 and finally to 26?

**Comment by etanol** [comment]
I'm closing this to reduce the issue noise.  Reopen if necessary.
