### ISSUE TITLE
Insufficient RFC-3066 support.

### ISSUE THREAD

**Issue by jenstroeger** [python-babel/babel#690]
Given that [RFC 3066](https://www.ietf.org/rfc/rfc3066.txt) defines the syntax of a language tag ([link](https://tools.ietf.org/html/rfc3066.html#section-2.1)) as follows:

> The language tag is composed of one or more parts: A primary language subtag and a (possibly empty) series of subsequent subtags.
> 
> The syntax of this tag in ABNF [RFC 2234] is:
> 
>    Language-Tag = Primary-subtag *( "-" Subtag )
>    Primary-subtag = 1*8ALPHA
>    Subtag = 1*8(ALPHA / DIGIT)

particularly

> […] The character "-" is HYPHEN-MINUS (ABNF: %x2D).

I am surprised to see Babel default to underscore notation:
```python
>>> babel.Locale.parse("en_US")
Locale('en', territory='US')
>>> babel.Locale.parse("en-US")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 268, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/…/lib/python3.7/site-packages/babel/core.py", line 1094, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got 'en-us'
>>> babel.Locale.parse("en-US", sep="-")
Locale('en', territory='US')
>>> str(babel.Locale.parse("en_US"))
'en_US'
```
While I can grumbingly accept the use of the extra `sep` parameter when parsing a language tag (why not built that in?), I do think that the default [`__str__`](https://github.com/python-babel/babel/blob/4fa749b918810b52a63b312d82e4003e24db0406/babel/core.py#L357-L359) should return a proper and RFC compatible string (i.e. [`get_locale_identifier()`](https://github.com/python-babel/babel/blob/4fa749b918810b52a63b312d82e4003e24db0406/babel/core.py#L1118-L1133) ought to default to `sep="-"`).

Why the incompatibility?

**Comment by akx** [comment]
`Locale.parse()` does not parse RFC 3066 _language tags_, but [ISO/IEC 15897](https://en.wikipedia.org/wiki/ISO/IEC_15897) identifiers as used by e.g. [UNIX locales](https://en.wikipedia.org/wiki/Locale_(computer_software)) and [Java's `Locale`](https://docs.oracle.com/javase/6/docs/api/java/util/Locale.html#toString()).

They do happen to be similar enough that using `sep="-"` does what you want most of the time.

**Comment by jenstroeger** [comment]
@akx, thanks for the info, that makes sense!

**Comment by jenstroeger** [comment]
@akx, I know this issue is closed but I wanted to gauge interest in a related matter. I work a lot with XML and therewith [RFC 3066](https://www.ietf.org/rfc/rfc3066.txt) language identifiers (see also the [`xsd:language`](http://www.datypic.com/sc/xsd/t-xsd_language.html) schema type).

I think it makes sense to consider language a subset of a locale. Interfacing with XML though, a `Locale` needs to be serialized into a RFC 3066 string, thus
```python
>>> import babel
>>> l = babel.Locale.parse("en_US")
>>> str(l)
'en_US'
```
won’t work. A function like this one help:
```python
>>> def rfc3066(l):
...     if l.territory:
...         return f"{l.language}-{l.territory}"
...     return l.language
... 
>>> 
>>> rfc3066(l)
'en-US'
```
Monkey-patching this function onto existing `Locale` objects is ugly, but subclassing `Locale` doesn’t work because [`Locale.parse()`](http://babel.pocoo.org/en/latest/api/core.html?highlight=parse#babel.core.Locale.parse) doesn’t take a factory. Any chance a function like this could be added to the `Locale` class? If a `Locale` would be iterable then
```
>>> babel.core.get_locale_identifier(*l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_locale_identifier() argument after * must be an iterable, not Locale
```
would be useful, too. But
```
>>> babel.core.get_locale_identifier((l.language, l.territory, None, None,), sep="-")
'en-US'
```
is rather clumsy.

**Comment by akx** [comment]
I don't see anything wrong with a `rfc3066` property if it's spec-compliant; feel free to make a PR :)

**Comment by ced-mos** [comment]
@akx I know this issue has been closed. However as it is related to my goal of better supporting rfc3066 when using the command line command `pybabel extract xxx` I thought I would contact you first before creating an new issue.

My goal is to add a mean to be able to work from the CLI with language tags based on the rfc3066, e.g. `en-US`. However, I was not able to find a mean to do that yet. A simple solution based on your [workaround](https://github.com/python-babel/babel/issues/690#issuecomment-579102319) would be adding an additional command option, e.g. `--locale-separator=<sep>`. However, does there exist already a solution to my problem? If not, would this be a feasible solution from the maintainers perspective?
