### ISSUE TITLE
HTTPS website

### ISSUE THREAD

**Issue by jayvdb** [python-babel/babel#693]
Hi, I noticed that https://babel.pocoo.org/ shows "Warning: Potential Security Risk Ahead" in Firefox because it has a wrong certificate for that domain.

As it is a RTD site, maybe https://github.com/buildout/buildout/issues/489 provides some useful hints on what could be wrong.

**Comment by jayvdb** [comment]
Note there is also a problem with https://sphinx.pocoo.org/

**Comment by Talhahpatelia** [comment]
The solution is to get a certificate from an open-source certificate company, e.g(Certbot).

I can easily fix but will need access to the server.  

https://certbot.eff.org/

👍

**Comment by akx** [comment]
babel.pocoo.org is on Read The Docs these days. I just enabled "force HTTPS" on there, which seems to have done the trick.
