### ISSUE TITLE
dev-python/Babel-2.6.0 crash for Chinese locale

### ISSUE THREAD

**Issue by LuciusV** [python-babel/babel#695]
Hello,
my flask application crashes in file 
"/usr/lib64/python3.6/site-packages/babel/core.py", line 1094, in parse_locale
```
if not lang.isalpha():
    raise ValueError('expected only letters, got %r' % lang)
```

ValueError: expected only letters, got 'zh-cn'

because locale name for Chinese is 'zh-cn' and cannot be matched with isalpha()

**Comment by akx** [comment]
Hi there! 

For specifiers like that, you will need to use `Locale.parse()`, not the `Locale()` constructor directly.

**Comment by LuciusV** [comment]
I checked flask-babel code, they actually use Locale.parse() in code
If I do dirty hack like 
`if lang == 'zh-cn':
    lang = 'zh'`
in python3.6/site-packages/babel/core.py
my application stops to crash.
I am not sure whether it flask-babel bug or babel bug...

**Comment by akx** [comment]
Ah, I'm sorry, you'll also have to separate the components with an underscore by default:
https://github.com/python-babel/babel/blob/0cfa69e087a24364ba788ff9d862949b65f0ff12/babel/core.py#L1043

There was recent discussion about that in #690.

**Comment by LuciusV** [comment]
Solved it by changing locale to 'zh_CN' having underscore in config, thanks!
