### ISSUE TITLE
Python version check in setup.py

### ISSUE THREAD

**Issue by rjollos** [python-babel/babel#70]
Trac uses Babel, and the latest version of Trac supports Python 2.5. For a Trac instance running Python <= 2.5, a [messy traceback](http://trac.edgewall.org/ticket/11258#comment:11) can result from installing Babel. Would you be willing to add a Python version check in setup,py, as shown [here](http://trac.edgewall.org/ticket/11258#comment:12)?

**Comment by sils1297** [comment]
@rjollos thanks for submitting this bug report! Marking this an easy fix for beginners. This will not be backported to the babel 2 version as it is more or less a "feature".

**Comment by rjollos** [comment]
I created pull request #236.

**Comment by rjollos** [comment]
#239 revises #236 to address requests made in #236 pull request.

**Comment by sils1297** [comment]
@rjollos FYI, you can also put a `Fixes https://github.com/python-babel/babel/issues/70` in the commit message to automatically track all commit revisions in the issue. (Please use the full URL for this as repository adresses may change in the future.)

**Comment by sils1297** [comment]
Fixed in https://github.com/python-babel/babel/commit/6a9f60f98a593014837dbb0625c85e219d842be7
