### ISSUE TITLE
Possible parse numbers with SI prefix?

### ISSUE THREAD

**Issue by hildogjr** [python-babel/babel#704]
Is it possible use `babel` (the number / units sub library) to parse number in a string format with SI prefixes and get the `Decimal` object? E.g:

1/2 -> Decimal(0.5)
1m -> Decimal(1e-3)
1m2 -> Decimal(1.2e-3) (used in electronics)

**Comment by akx** [comment]
Sorry for the late reply!

I don't think that's currently possible, but that shouldn't be too hard to implement with a regular expression by yourself.

In particular, the first example is implemented precisely by the `fractions` built-in library.
