### ISSUE TITLE
Drop pytz as a dependency

### ISSUE THREAD

**Issue by pganssle** [python-babel/babel#716]
Since the introduction of [PEP 495](https://www.python.org/dev/peps/pep-0495/), `pytz`'s unusual API has become [more of a liability than an asset](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html). With the introduction of [PEP 615](https://www.python.org/dev/peps/pep-0615/) (the standard library `zoneinfo` module), there is really no good reason to continue using `pytz` at this point, and it is probably a good time to transition away from it. This is one of the more popular projects using `pytz`, and I think it would be a good idea to start transitioning away. 

I will note that Stuart Bishop, author and maintainer of `pytz`, is [planning to make `pytz` a thin wrapper around `zoneinfo`](https://discuss.python.org/t/pep-615-support-for-the-iana-time-zone-database-in-the-standard-library/3468/16) at some point, and so it is probably a good idea to get ahead of the curve on this.

I took a quick look to see how easy it would be to do, and I found that the `pytz`-specific integration is a bit deeper than I had hoped, and a straightforward adoption of `zoneinfo.ZoneInfo` would run into the following problems:

1. This project still supports Python 2.7, and [`backports.zoneinfo`](https://pypi.org/project/backports.zoneinfo/) only supports Python 3.6+.
2. The [`get_timezone` function](https://github.com/python-babel/babel/blob/e7e4265d9a037ac38bba99f8513fb9e48a1081ba/babel/dates.py#L176) explicitly returns `pytz` zones, which (as we noted), have a different API than standard `tzinfo` zones.
3. The [`get_next_timezone_transition`](https://github.com/python-babel/babel/blob/e7e4265d9a037ac38bba99f8513fb9e48a1081ba/babel/dates.py#L197) function relies on private implementation details of `pytz`, and it is not possible to write analogous code for `zoneinfo`, which stores transition information in opaque C structs. Presumably this will become a problem in the future when `pytz` becomes a thin wrapper around `zoneinfo` *anyway*.

I think that we can solve problem 1 easily enough by adding a compatibility function that uses `dateutil.tz` in Python 2.7 only — `dateutil.tz` has similar functionality to `zoneinfo.ZoneInfo`.

Depending on how you feel about breaking changes and how much you intend to explicitly support the `pytz` interface, I think you can solve problem 2 with a thin wrapper class deprecating the `pytz` interface, like this:

```python
class TzWrapper(tzinfo):
    def __init__(base_tzinfo):
        self._base_tzinfo = base_tzinfo

    def utcoffset(self, dt):
        return self._base_tzinfo.utcoffset(dt)

    def dst(self, dt):
        return self._base_tzinfo.dst(dt)

    def tzname(self, dt):
        return self._base_tzinfo.tzname(dt)

    def fromutc(self, dt):
        dt_base = dt.replace(tzinfo=self._base_tzinfo)
        dt_out = self._base_tzinfo.fromutc(dt_base)
        return dt_out.replace(tzinfo=self)

    def localize(self, dt, is_dst=False):
        raise_pytz_warning()
        # Some more involved code to map is_dst to fold goes here
        ...
        return dt.replace(tzinfo=self, fold=fold)

    def normalize(self, dt):
        raise_pytz_warning()
        return dt.astimezone(self)
```

Where `raise_pytz_warning()` would raise a warning telling people to stop calling `localize` and `normalize`, as the wrapper class will be dropped in a future version.

Problem 3 is the hardest to solve and *also* is likely to affect you regardless of whether or not you choose to adopt `backports.zoneinfo`. There's no public interface on any time zone provider that allows for this, so I think your options are:

1. Deprecate and then remove this function entirely.
2. Make the case for why this functionality is important, in which case we can add it to `zoneinfo` for Python 3.10, and add it to `backports.zoneinfo` now.
3. Write a TZif parser (this is actually easier than it sounds), and try to find the corresponding TZif file (this is fragile, unfortunately) to get the next transition.
4. Don't use *any* existing time zone implementations and write your own that exposes this.

**Comment by pganssle** [comment]
I'll note that in a search on github, the only references to `get_next_timezone_transition` I find are forks or vendored versions of this repository and its documentation, and [this function](https://github.com/mitsuhiko/worldtime-scheduler/blob/0fb068d09a824502b2051bbc0c132f3005a9107a/data/convert.py#L75-L123), which is in a project that hasn't had any commits in 7 years, so there's a good chance that no one is actually *using* this function any longer.

**Comment by mitsuhiko** [comment]
I would say that removing `get_next_timezone_transition` is fine. Knowing when transitions are happening is very useful but this function did not expose a sane enough interface to be useful here.

**Comment by homeworkprod** [comment]
> 1. This project still supports Python 2.7, and [`backports.zoneinfo`](https://pypi.org/project/backports.zoneinfo/) only supports Python 3.6+.
> 
> […]
> 
> I think that we can solve problem 1 easily enough by adding a compatibility function that uses `dateutil.tz` in Python 2.7 only — `dateutil.tz` has similar functionality to `zoneinfo.ZoneInfo`.

As of 58de8342f865df88697a4a166191e880e3c84d82, `master` requires at least Python 3.6, so the first problem is solved for upcoming releases.

**Comment by akx** [comment]
@pganssle @mitsuhiko Following #852 (to be merged for Babel 2.10), `get_next_timezone_transition()` is marked deprecated with no replacement and we can 🚮  it altogether for the following version of Babel.

**Comment by ds-cbo** [comment]
May I ask for an update on this issue? With Django 4.x deprecating pytz in favour of zoneinfo and with Django 3.x losing LTS this year, we are looking to remove the pytz dependency altogether to avoid (accidental) incompatibilities when passing datetimes between libraries. It currently seems that Babel would be blocking that.

**Comment by mitsuhiko** [comment]
I don't have an update here but I would be curious if there is an actual risk of this happening. In theory the tzinfo interface did not change (at least from my understanding) so the objects should work interchangeably.

**Comment by ds-cbo** [comment]
In theory, it should indeed not matter if everyone adheres to the `tzinfo` interface and doesn't accidentally call `.normalize` or `.localize` anywhere, but we've already found some dependencies that do/did this. Babel seems to be in the clear here on closer inspection, though I have not tested it yet.

However, there are already some incompatibilities in timezone data, since the `America/Ciudad_Juarez` timezone does exist in `zoneinfo` but not in `pytz` on our systems. While we're not extremely likely to hit it in practice, Babel's `get_timezone` would miss it when that's passed by name from others using `zoneinfo`.

Would it be okay if I send in a PR to remove the hard `pytz` dependency (or only depend on it under python 3.9) and have Babel's `get_timezone(str)` default to `zoneinfo` and fall back to `pytz` to look up with? If only for the peace of mind that we don't have to actively keep track of any more future incompatibilities between these libraries.

**Comment by akx** [comment]
@ds-cbo A pull request is very welcome.
