### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'cache'

### ISSUE THREAD

**Issue by judgewooden** [python-babel/babel#717]
`pybabel extract -F babel.cfg -o messages.pot .`

does not recognize tags `{% cache 60, key %}` and `{% endcache %} ` using flask_caching. 

Is this a problem from pybabel or do I need initialize somehow?

**Comment by judgewooden** [comment]
pybabel 2.8.0

**Comment by akx** [comment]
See #444, and more closely https://github.com/python-babel/babel/issues/444#issuecomment-251043372 -- you will need to tell Babel which Jinja extensions to load so parsing is possible.

**Comment by sezeryesiltas** [comment]
we need to add flask_caching.jinja2ext.CacheExtension to our babel config file
