### ISSUE TITLE
No changelog for 2.8.0 at http://babel.pocoo.org/en/latest/?

### ISSUE THREAD

**Issue by jonkiparsky** [python-babel/babel#718]
I don't know if this is intentional and I'm missing something, but when I was checking the current version status of babel, I was confused to find that the latest version listed on http://babel.pocoo.org/en/latest/ was 2.7.0, since I was seeing 2.8.0 installed on our project. Had to look at the tags here to clear that up.

**Comment by akx** [comment]
This was fixed just now in #822. The automatic docs builds weren't... automatic.
