### ISSUE TITLE
What about language aliases?

### ISSUE THREAD

**Issue by jenstroeger** [python-babel/babel#721]
This issue, I think, is related to https://github.com/python-babel/babel/issues/39 and https://github.com/python-babel/babel/issues/285.

I just ran into a somewhat surprising problem when I used [ISO 639/2](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) language codes:
```
>>> import babel
>>> babel.__version__
'2.8.0'
>>> babel.Locale("eng")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'eng'
>>> babel.Locale("en")
Locale('en')
>>> babel.Locale("ita")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'ita'
>>> babel.Locale("it")
Locale('it')
>>> babel.Locale("ger")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/…/lib/python3.7/site-packages/babel/core.py", line 168, in __init__
    raise UnknownLocaleError(identifier)
babel.core.UnknownLocaleError: unknown locale 'ger'
>>> babel.Locale("de")
Locale('de')
```
Looking at the [current CLDR v36](https://unicode.org/Public/cldr/36/) I noticed a file `common/supplemental/supplementalMetadata.xml` that contains a number of `<languageAlias>` elements, and it would be easy to generate an alias map:
```
>>> import lxml.etree
>>> xml = lxml.etree.parse("common/supplemental/supplementalMetadata.xml")
>>> alias_map = {e.attrib["type"]: e.attrib["replacement"] for e in xml.xpath("//languageAlias") if e.attrib["reason"] in ("overlong", "bibliographic",)}
>>> # alt: alias_map = {e.attrib["type"]: e.attrib["replacement"] for e in xml.xpath("/supplementalData/metadata/alias/languageAlias[@reason = 'overlong' or @reason = 'bibliographic']")}
>>> alias_map["eng"]
'en'
>>> alias_map["ita"]
'it'
>>> alias_map["ger"]
'de'
```
That map could then be used by the [`Locale` constructor](https://github.com/python-babel/babel/blob/e7e4265d9a037ac38bba99f8513fb9e48a1081ba/babel/core.py#L140-L168), e.g. like
```python
#: the language code
self.language = alias_map.get(language, language)
```
Alternatively, adding a helper function to perform a language identifier mapping would be useful too:
```python
lang = "ita"
try:
    l = babel.Locale(lang)
except babel.core.UnknownLocaleError:
    l = babel.Locale(babel.alias_language_code(lang))
# Do something with l.
```
**Addendum:** I also noticed the [`core.negotiate_locale()` function](https://github.com/python-babel/babel/blob/e7e4265d9a037ac38bba99f8513fb9e48a1081ba/babel/core.py#L980-L1040) which may be a good fit, and the aforementioned `alias_map` could be merged into [`core.LOCALE_ALIASES`](https://github.com/python-babel/babel/blob/e7e4265d9a037ac38bba99f8513fb9e48a1081ba/babel/core.py#L80-L89).

I haven’t checked whether that alias map is a complete ISO 639/2 map, but it’s a beginning… 😉

**Comment by akx** [comment]
In general, you shouldn't use `babel.Locale()` unless you know what you're doing. (We know that's a silly API, but we're stuck with it until 3.x.)

Instead, use `Locale.parse()`:

```
>>> import babel
>>> babel.Locale("ita")
babel.core.UnknownLocaleError: unknown locale 'ita'
>>> babel.Locale.parse("ita")
Locale('it', territory='IT')
```

**Comment by jenstroeger** [comment]
Great, that works!
