### ISSUE TITLE
I think you should limit this to POST operations only as PUT, DELETE, GET, HEAD, OPTIONS, & TRACE are supposed to be idempotent already as per the HTTP specification. If you want to be able to send this header for these other methods, then the service should just ignore it. But, I think it better to just limit this to POST.

### ISSUE THREAD

**Issue by mishal193** [python-babel/babel#722]
I think you should limit this to POST operations only as PUT, DELETE, GET, HEAD, OPTIONS, & TRACE are supposed to be idempotent already as per the HTTP specification. If you want to be able to send this header for these other methods, then the service should just ignore it. But, I think it better to just limit this to POST.

To implement this robustly, the service needs to update it table of GUIDs AND perform the POST operation as an atomic/transacted unit. In other words, the service is not fault tolerant if it adds the guid to its table and then crashes before performing the POST operation. If this happens, the client retries, the service thinks the operation is already done, and never actually creates anything. The reverse is also problematic (but perhaps less so): the service performs the POST operation and then crashes before it adds the guid to its table. Now, the service doesn't know the operation was done and if the client retries, the operation is performed twice - this is similar to 2 PUTs in a row.

Having a time limit is great (like 24 hours) because the guid table shouldn't grow without bounds. Of course, this will increase latency and for some services, this may cause the table to become quite big. We need something here; maybe we can reduce the 24hr limit to 12hr or something - the exact time limit can be debated later. I think it best if each service can't decide its own time limit.

- _Originally posted by @JeffreyRichter in https://github.com/microsoft/api-guidelines/issues/209#issuecomment-656317896_

_Originally posted by @mishal193 in https://github.com/mishal193/automatic-goggles/issues/6_

**Comment by akx** [comment]
Babel doesn't do any HTTP stuff by itself. I'm not sure why this is here. Closing.

**Comment by mishal193** [comment]
DELETE

‫في 31‏/07‏/2020 الساعة 9:42 م، كتب/كتبت ‏Aarni Koskela ‏<notifications@github.com>:‬

﻿

Babel doesn't do any HTTP stuff by itself. I'm not sure why this is here. Closing.
