### ISSUE TITLE
Currencies dict is returning currencies display text in lowercase for Locale pt-PT

### ISSUE THREAD

**Issue by peca11** [python-babel/babel#727]
Currencies dict is returning currencies display text in lowercase for Locale pt-PT
I'm using Babel==2.8.0
It was working fine on Babel==2.3.4

Example:

Working fine in de-DE
```
from babel.core import default_locale, Locale
l = Locale('de', 'DE')

l.currencies('EUR')
Out: 'Euro'

l.currencies['USD']
Out: 'US-Dollar'

l.currencies['GBP']
Out: 'Britisches Pfund'

l.currencies['MZN']
Out: 'Mosambikanischer Metical'
```
If the locale is set to pt-PT it returns the currency text in lowercase 
```
from babel.core import default_locale, Locale
l = Locale('pt', 'PT')

l.currencies['EUR']
Out: 'euro'

l.currencies['USD']
Out: 'dólar dos Estados Unidos'

 l.currencies['GBP']
Out: 'libra esterlina britânica'

l.currencies['MZN']
Out: 'metical moçambicano'

```

**Comment by akx** [comment]
This is as expected, as the spelling for currencies in many languages, apparently including Portuguese, is lower-case. (You can see that `'USD'` does have the "Estados Unidos", "United States", capitalized).

You'll find a similar behavior for e.g. my native Finnish (`fi-FI`).'

Please feel free to reopen if you have further questions.
