### ISSUE TITLE
Would you guys like to take ownership of django-babel

### ISSUE THREAD

**Issue by graingert** [python-babel/babel#74]
I've ported BabelDjango to github:

https://github.com/graingert/django-babel

Would you guys like to take over ownership?

**Comment by sils1297** [comment]
@graingert currently we're struggling with this repository, manpower-wise, so adding another repository to our workload is not a good idea IMO. I think it would be cool to move the django-babel repository into the python-babel organization so you gain a bit more public visibility and we can use our teams to manage contributors.

Would you be interested in that?

**Comment by sils1297** [comment]
That implies, you stay maintainer of your repo under our umbrella and we all try to help out everyone :)

**Comment by graingert** [comment]
sounds good to me

**Comment by sils1297** [comment]
@graingert cool, can you join https://gitter.im/python-babel/babel so we can talk about this?

**Comment by sils1297** [comment]
Done.
