### ISSUE TITLE
get_timezone_location does not work with python's ZoneInfo object

### ISSUE THREAD

**Issue by youtux** [python-babel/babel#740]
`get_timezone_location` does not render correctly the ZoneInfo objects. These are part of python as of python 3.9 (and available as backport).

MCVE:
`$ pip install backports.zoneinfo babel`
```
# tz.py
from babel.dates import get_timezone_location
from backports import zoneinfo
import pytz

ams_native = zoneinfo.ZoneInfo("Europe/Amsterdam")
ams_pytz = pytz.timezone("Europe/Amsterdam")

print(get_timezone_location(ams_pytz))  # output: "Netherlands Time"
print(get_timezone_location(ams_native))  #  output: "Unknown Region (CEST) Time"
```
Python version: 3.6.11
babel version: 2.8.0

I think this can be easily fixed by checking the `timezone.key` attribute. Shall I make a PR?

**Comment by akx** [comment]
Please do! :)
