### ISSUE TITLE
tests fail with pytest 6

### ISSUE THREAD

**Issue by eli-schwartz** [python-babel/babel#747]
Attempting to rebuild [python-babel 2.8.0](https://www.archlinux.org/packages/community/any/python-babel/) for Arch Linux without changes, but with a system pytest 6 package, I get the following error:

```
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/python-babel/src/babel-2.8.0, configfile: setup.cfg
collected 0 items / 1 error

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
Direct construction of DoctestModule has been deprecated, please use DoctestModule.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
=========================== short test summary info ============================
ERROR 
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.09s ===============================
```

**Comment by akx** [comment]
Fixed by #752. Would a 2.8.1 patch release help?

**Comment by eli-schwartz** [comment]
Yes please, if that would be convenient. :)

We are currently doing python 3.9 rebuilds, so we need to have the fix ASAP. And it's more convenient to bump the version to 2.8.1 than to backport the fix.

**Comment by akx** [comment]
@eli-schwartz 2.8.1 is now up on PyPI and as a tag in this repo. Sorry for the inconvenience and thanks for the bug report!

A 2.9.0 release with functional changes over 2.8.0 is also forthcoming – maybe not today but soon enough 😄
