### ISSUE TITLE
Localized name for pt_BR missing since > 2.4

### ISSUE THREAD

**Issue by felixoi** [python-babel/babel#751]
I can't upgrade my babel installation because after version 2.4 babel is missing
the following localized name:

```
babel.Locale.parse('pt-BR', sep='-').languages['pt_BR']
```

Why has it been removed?

**Comment by akx** [comment]
Hi @felixoi – did you find a solution, or is this still a problem?

**Comment by felixoi** [comment]
I think this was moved around in CLDR. pt_PT has now a localized name and pt_BR is now the normal display name.
