### ISSUE TITLE
Missing tag in the github project

### ISSUE THREAD

**Issue by Foxboron** [python-babel/babel#762]
Seems like there was a release to `2.9.0` which was uploaded to pypi, but the release was not tagged on github. Could this be fixed or should I move to the pypi release tarballs?

**Comment by akx** [comment]
My bad!

I've pushed the tag and made a GitHub release too. https://github.com/python-babel/babel/releases/tag/v2.9.0

**Comment by Foxboron** [comment]
Thanks!
