### ISSUE TITLE
Missing documentaries 

### ISSUE THREAD

**Issue by jveer634** [python-babel/babel#766]
There is no html folder or .html files in docs folder that documents the babel.
Please have a look at the screenshot below.

![20201209_000216](https://user-images.githubusercontent.com/47923507/101525966-0d989f00-39b2-11eb-8dbe-764775854b4b.jpg)

**Comment by akx** [comment]
The documentation is compiled into HTML from those RST files using Sphinx.

**Comment by jveer634** [comment]
Sorry for that. Beginner mistake
