### ISSUE TITLE
PluralRule lacking support for new operands

### ISSUE THREAD

**Issue by qixils** [python-babel/babel#786]
# Overview Description

PluralRule is not updated to conform to the latest versions of CLDR and does not support the [new operands `c` or `e`](https://unicode.org/reports/tr35/tr35-numbers.html#Plural_rules_syntax)

# Steps to Reproduce

Attempt to parse French plural rules: `PluralRule.parse({"one":"i = 0,1","many":"e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5","other":""})`

# Actual Results

Throws a RuleError: `malformed CLDR pluralization rule.  Got unexpected 'e'`

# Expected Results

Parses the rules successfully

# Reproducibility

Consistent

# Additional Information:

Using babel-2.9.1 from pypi

**Comment by akx** [comment]
Babel 2.9 does not support those new rules, that's correct. 

CLDR 40 support is coming in #826 (likely Babel 2.10); it will have support for parsing those operands (but nothing else around them).
