### ISSUE TITLE
Wrong timezone name when using zoneinfo

### ISSUE THREAD

**Issue by jaap3** [python-babel/babel#812]
## Overview Description

While running a project's test suite using Django 4.0a1 I noticed a failing test related to time formatting. After some debugging I've boiled down the root cause to Django's switch from `pytz` to `zoneinfo` and `python-babel`'s `format_time` function giving the wrong result.

## Steps to Reproduce

```
import datetime
import zoneinfo
from babel.dates import format_time

tz = zoneinfo.ZoneInfo('Europe/Amsterdam')
start = datetime.datetime(2020, 11, 12, 10, 15, tzinfo=tz)
format_time(start, 'z', locale='nl')
```

## Actual Results

`'CEST'`

## Expected Results

`'CET'`

## Reproducibility

Using `strftime` (i.e. `start.strftime('%Z')`) the result is as epected.
Using `pytz` (i.e. `tz = pytz.timezone('Europe/Amsterdam'); start = tz.localize(...)`) the result is also as expected.

**Comment by jaap3** [comment]
Seems like we were doing it wrong (but it worked), using format_datetime does give the correct result. Using format_time doesn't take the date into account, so the result was always CET.

I also had the actual and expected results in the wrong order, sorry for the noise ☺️.

**Comment by akx** [comment]
@jaap3 Glad you got it sorted out! For the record, Babel 2.12 will prefer `zoneinfo` to `pytz`: https://github.com/python-babel/babel/pull/940
