### ISSUE TITLE
[ENH] get (default) currency code for given locale

### ISSUE THREAD

**Issue by ericzolf** [python-babel/babel#815]
## Overview Description
Add a function to get a countrie's currency (or currencies) as code

**Comment by akx** [comment]
Would `get_territory_currencies` work for you? See #42, b409813eff5142e1856e5e57c221b72d8d5b978b.

**Comment by ericzolf** [comment]
Looks good to me, with perhaps two questions:

1. is there an easy way to extract the territory from the locale?
2. is the list order of currencies? e.g. do I get the most common currency if I take the fist element? 
Thanks!

**Comment by akx** [comment]
1. `locale.territory` - but it might not be set if it's not known (e.g. `en` has no territory, `en_US` has). In either case, an user could be in Finland (where we use EUR), but like their software in `en_US`...
2. According to the [docs](https://babel.pocoo.org/en/latest/api/numbers.html#babel.numbers.get_territory_currencies) the list is in chronological order, so you will likely want the _last_ one for the most recently enacted tender.
