### ISSUE TITLE
Large float on format_currency throw InvalidOperation when quantized

### ISSUE THREAD

**Issue by Glandos** [python-babel/babel#821]
## Overview Description
When using very large float, `quantize` call fails.

## Steps to Reproduce

1. `from babel.numbers import format_currency`
2. `format_currency(9347242149381274732472348728748723473278472843.12, 'EUR')`

## Actual Results
```ipython
In [14]: format_currency(9347242149381274732472348728748723473278472843.12, 'EUR')
---------------------------------------------------------------------------
InvalidOperation                          Traceback (most recent call last)
<ipython-input-14-1ba3e756d2f0> in <module>
----> 1 format_currency(9347242149381274732472348728748723473278472843.12, 'EUR')

/usr/lib/python3/dist-packages/babel/numbers.py in format_currency(number, currency, format, locale, currency_digits, format_type, decimal_quantization)
    517                 "%r is not a known currency format type" % format_type)
    518 
--> 519     return pattern.apply(
    520         number, locale, currency=currency, currency_digits=currency_digits,
    521         decimal_quantization=decimal_quantization)

/usr/lib/python3/dist-packages/babel/numbers.py in apply(self, value, locale, currency, currency_digits, decimal_quantization, force_frac)
    994         # A normal number pattern.
    995         else:
--> 996             number = self._quantize_value(value, locale, frac_prec)
    997 
    998         retval = ''.join([

/usr/lib/python3/dist-packages/babel/numbers.py in _quantize_value(self, value, locale, frac_prec)
   1063     def _quantize_value(self, value, locale, frac_prec):
   1064         quantum = get_decimal_quantum(frac_prec[1])
-> 1065         rounded = value.quantize(quantum)
   1066         a, sep, b = "{:f}".format(rounded).partition(".")
   1067         number = (self._format_int(a, self.int_prec[0],

InvalidOperation: [<class 'decimal.InvalidOperation'>]

```

## Expected Results
The number that was passed in.
I guess that it is somewhat difficult because it's transformed into scientific notation.

**Comment by Glandos** [comment]
That's a workaround, but since there's always a limit, we decided to check for high (and usually meaningless) values: https://github.com/spiral-project/ihatemoney/pull/989
In our project, this is a user input, and once stored in a database, it was impossible to format it for display in the web output, resulting in an error 500 for everyone. Kind of DoS :)

**Comment by akx** [comment]
It sounds like your formatting should fall back to a "dumber" representation if Babel is unable to format the number, not that you limit what you ingest :)

In any case, I'll close this for now since a workaround is available and documented herein.

**Comment by Glandos** [comment]
I think we could do that, but since we are targeting a "budget manager for friends", I think that limiting input to number less than 100,000,000,000 is OK :wink: 

However, we could have surrounded the call to `format_currencies` with a `try … except` block. But this **should** be mentioned in the docs of https://babel.pocoo.org/en/latest/api/numbers.html#babel.numbers.format_currency that `InvalidOperation` can be thrown for some numbers.
