### ISSUE TITLE
website reflects docs for 2.7.0, not current

### ISSUE THREAD

**Issue by jepler** [python-babel/babel#822]
## Overview Description
It appears that the website docs may not be updating.

## Steps to Reproduce

1. Follow the readme link to http://babel.pocoo.org/ which redirects to http://babel.pocoo.org/en/latest/
2. Note in the table of contents that the latest changelog entry is for 2.7.0
3. Note that the copyright date is 2019
4. Follow the link to 'builds' within readthedocs and note that the last build was "1 year, 11 months ago" https://readthedocs.org/projects/python-babel/builds/
 
## Actual Results
Old version information, nearly 2 years old, is reflected

## Expected Results
Current version information is reflected

## Reproducibility
Every time

## Additional Information
Thank you for babel.

**Comment by akx** [comment]
For some reason, the docs aren't being built automatically. I'll look into that – but for the time being, the documentation now is for 2.9.1! 🎉  http://babel.pocoo.org/en/stable/

**Comment by akx** [comment]
The RTD GitHub webhook is also now enabled, so new versions should automagically get docs.

**Comment by jepler** [comment]
Thank you!
