### ISSUE TITLE
Release 2.9.1 is a year old

### ISSUE THREAD

**Issue by jdimmerman** [python-babel/babel#849]
Hey - The latest release of babel is almost a year old. Any plans on publishing a new version? We'd love to use some of the latest features in the codebase.

Thanks!

**Comment by akx** [comment]
Certainly - I'll try to get to it soon!

**Comment by jdimmerman** [comment]
You rock, thanks @akx!

**Comment by Niveshkrishna** [comment]
Definitely we could make good use of a new release. Waiting for `--ignore-dirs` :balloon:

**Comment by akx** [comment]
2.10.0 has been released. 🎉 

(Didn't even take a year... 😁 )

* PyPI: https://pypi.org/project/Babel/2.10.0/
* GH: https://github.com/python-babel/babel/releases/tag/v2.10.0
