### ISSUE TITLE
Currency symbol locale changes on latest version

### ISSUE THREAD

**Issue by latusaki** [python-babel/babel#862]
## Overview Description

I have got the following unit test failing when upgrading from babel 2.9.1 to 2.10.1. Is this change intended / correct ?

## Steps to Reproduce
```
> from babel import numbers
> numbers.format_currency(number=120, currency="GBP", locale="en_AU")
````
## Actual Results
'GBP120.00'
## Expected Results
'£120.00'

## Additional information

Another unit test that started failing is the following:

`numbers.format_currency(number=120, currency="USD", locale="en_AU")`

Result in 2.9.1 : "US$120.00"
Result in 2.10.1 : "USD120.00"

**Comment by akx** [comment]
Hi!

According to the CLDR Survey Tool, those are the winning "spelling"s for US dollars and English pounds in `en_AU`:

* https://st.unicode.org/cldr-apps/v#/en_AU/C_NAmerica/
* https://st.unicode.org/cldr-apps/v#/en_AU/C_NWEurope/

**Comment by latusaki** [comment]
very bizzare, I guess that means python-babel is down the right thing !

**Comment by DragosChirila** [comment]
I have a similar issue.

When upgrading from 2.9.1 to 2.10.1 I have tests failing:
```
AssertionError: 'INR99.99' != '₹99.99'
- INR99.99
? ^^^
+ ₹99.99
? ^
```

It looks like now, the symbol for India rupees is now INR and not ₹.

I am running a Django app and my local conversion function is
```
    from babel.numbers import format_currency

    @classmethod
    def format_currency3(cls, price, currency=settings.TALI_SHOPPING_CURRENCY):
        """ price assumed to be in the smallest currency unit
        """
        return (
            format_currency(
                round(price / 100, 3),
                currency,
                locale=settings.TALI_SHOPPING_LOCALE,
                decimal_quantization=False
            )
        )
```
where in settings:
```
TALI_SHOPPING_LOCALE = 'en_AU'
TALI_SHOPPING_CURRENCY = 'INR'
```

It looks like changing to 
```
TALI_SHOPPING_LOCALE = 'en_IN'
```

fixes the tests... but I wanted to understand what has changed if possible :)

Thanks

**Comment by latusaki** [comment]
I'll mark this issue as closed, as it seems like babel is doing what it's supposed to. If thats wrong someone else can re-open
