### ISSUE TITLE
Issue with Plural? SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by samlehman** [python-babel/babel#867]
## Overview Description

I'm not too well versed with python syntax, so I'm not sure if this is an issue or not, but at the bottom of a traceback was babel's plural library, line 336:

```
File "/usr/local/lib/python3.4/dist-packages/babel/init_.py", line 20, in <module> from babel.core import UnknownLocaleError, Locale, default_locale, \
File "/usr/local/lib/python3.4/dist-packages/babel/core.py", line 16, in <module> from babel.plural import PluralRule
File "/usr/local/lib/python3.4/dist-packages/babel/plural.py", line 336 ('word', re.compile(fr'\b(and|or|is|(?:with)?in|not|mod|[\{"".join(_VARS)}])\b')), ^ 

SyntaxError: invalid syntax
```

code before:

`('word', re.compile(r'\b(and|or|is|(?:with)?in|not|mod|[{0}])\b'
.format(_VARS))),`

after:

`('word', re.compile(fr'\b(and|or|is|(?:with)?in|not|mod|[{"".join(_VARS)}])\b')),`

## Additional Information

We're using python 3.4.

https://github.com/python-babel/babel/commit/98620495670fa0e046d2e2e57a7a75dc8643119c# - line 324 <> 336

**Comment by jun66j5** [comment]
At least, Python 3.6+ is required since Babel 2.10.0, https://github.com/python-babel/babel/blob/v2.10.0/setup.py#L61

**Comment by jun66j5** [comment]
https://github.com/python-babel/babel/blob/v2.10.0/CHANGES.rst#version-290 says:

> This version, Babel 2.9, is the last version of Babel to support Python 2.7, Python 3.4, and Python 3.5.

**Comment by samlehman** [comment]
@jun66j5 Gotcha, thanks. We'll try locking to 2.9.1.

**Comment by akx** [comment]
Please consider upgrading your Python version - Python 3.4 has been end-of-life since 18 Mar 2019.
