### ISSUE TITLE
Move away from cgi.parse_header

### ISSUE THREAD

**Issue by domdfcoding** [python-babel/babel#873]
## Overview Description

`babel` currently uses `cgi.parse_header` [here](https://github.com/python-babel/babel/blob/d2d88da71cf8a67acdaccf48dc249f6e3567fafc/babel/messages/catalog.py#L428) to parse mime type headers.
The `cgi` module is deprecated in Python 3.11 by [PEP 594](https://peps.python.org/pep-0594/#cgi), and is scheduled for removal in 3.13. 
The recommended replacement is `email.message.Message`; there is an example in the PEP showing how to use it instead.

**Comment by hugovk** [comment]
Python 3.11 was [released on Monday](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk), so this deprecation warning is now showing up.

Do you have a rough idea when this will be released?

Thank you!

**Comment by akx** [comment]
@hugovk Babel 2.11.0 is freshly out of the oven! Find it at a PyPI CDN endpoint near you. 😁  https://github.com/python-babel/babel/releases/tag/v2.11.0

**Comment by hugovk** [comment]
Thank you! 🚀
