### ISSUE TITLE
Please release a bug fix release with the fix in #872 👍 

### ISSUE THREAD

**Issue by violuke** [python-babel/babel#883]
## Overview Description
Please can a bug fix release be made to PyPI?

The fix in #872 is resolving a significant issue for us and it would be great to get back into using PyPI releases rather than pointing to master. Thank you.

**Comment by akx** [comment]
Released in Babel 2.10.2:

* https://pypi.org/project/Babel/2.10.2/
* https://github.com/python-babel/babel/releases/tag/v2.10.2

Sorry for the delay.
