### ISSUE TITLE
Missing support for Tswana (tn)

### ISSUE THREAD

**Issue by TiBiBa** [python-babel/babel#899]
## Overview Description
It seems that Babel does not support Tswana.
`tn` is the ISO 639-1 code for this language but Babel returns the `babel.core.UnknownLocaleError: unknown locale 'tn'` error.

What is required to add this language to Babel or should this be fixed through Unicode CLDR? I couldn't find any info if Tswana is already listed there following [this](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/?jql=project%20%3D%20%22CLDR%22%20AND%20text%20~%20%22Tswana%22%20ORDER%20BY%20created%20DESC&keyword=pali&orderby=priority%20DESC) link.

**Comment by akx** [comment]
Unfortunately this needs to be fixed via the CLDR.

Adding support for project-local arbitrary languages has been talked about in the past (#454) but it requires quite some refactoring.

**Comment by Felienne** [comment]
I see your point but we are not talking about a project specific language in this case, but about Tswana, an actual language spoken by a few million people, and one that seems to already in the latest CLDR:

https://github.com/unicode-org/cldr/blob/62c90a357dc25911db60fcdf7d5a80119df27963/tools/cldr-code/src/main/resources/org/unicode/cldr/util/data/language_list.txt

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1003685/200412151-96dd60df-caae-44be-b829-210eaac9ecab.png">

So could you please reconsider, or help us understand how we can add it ourselves? No problem to do a bit of work for that!
