### ISSUE TITLE
Unable to export plural forms from javascript files

### ISSUE THREAD

**Issue by AndVK** [python-babel/babel#907]
## Overview Description

If you use the -k options to search for the desired functions when extracting localizable messages from javascript files, then the messages are not exported as plural forms

## Steps to Reproduce

1. Use command
```
pybabel extract -F babel.cfg -o messages.pot . -k t -k tn
```

2. We have .tsx file with the following code
<img src="https://user-images.githubusercontent.com/89656461/195330459-8523fdf7-9e16-483c-b6e8-3def0c8edc45.png" alt="drawing" width="400"/>

## Actual Results
We have messages.pot file with the following text
<img src="https://user-images.githubusercontent.com/89656461/195329342-896d25ba-9ea8-4f12-8e09-bf957e3eab62.png" alt="drawing" width="150"/>

## Expected Results
We have messages.pot file with the following text
<img src="https://user-images.githubusercontent.com/89656461/195328797-054460ea-4b90-41c1-97ea-da8dfa38b1f5.png" alt="drawing" width="200"/>

**Comment by jun66j5** [comment]
Try `-k tn:1,2` rather than `-k tn`.

**Comment by AndVK** [comment]
@jun66j5
Command ```pybabel extract -F babel.cfg -o messages.pot . -k t -k tn:1,2``` doesn't work correctly

**Comment by jun66j5** [comment]
Weird. Works fine on my environment.

### babel.cfg
```
[jinja2: **.html]
```

### src/test.html
```
<div>{{ tn('%s row', '%s rows', 42) }}</div>
```

```
$ pybabel extract -o messages.pot -F babel.cfg -k t -k tn:1,2 src
extracting messages from src/test.html
writing PO template file to messages.pot
```

### Results
```
# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-10-13 01:37+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: src/test.html:1
#, python-format
msgid "%s row"
msgid_plural "%s rows"
msgstr[0] ""
msgstr[1] ""

```

**Comment by jun66j5** [comment]
Sorry. I should try to use javascript extractor for *.tsx. It works.

### babel.cfg
```ini
[javascript: **.tsx]
```

### src/test.tsx
```tsx
<div>{tn('%s row', '%s rows', 42)}</div>
```

### Extraction
```
$ pybabel extract -o messages.pot -F babel.cfg -k t -k tn:1,2 src
extracting messages from src/test.tsx
writing PO template file to messages.pot
```

### Results: messages.pot
```po
# Translations template for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-10-13 04:07+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: src/test.tsx:1
#, python-format
msgid "%s row"
msgid_plural "%s rows"
msgstr[0] ""
msgstr[1] ""

```

**Comment by AndVK** [comment]
I did it! The command ```pybabel extract -o messages.pot -F babel.cfg -k t -k tn:1,2 src``` helped.
Thank you!
