### ISSUE TITLE
Is it possible to use the short number formats from CLDR?

### ISSUE THREAD

**Issue by DenverCoder1** [python-babel/babel#908]
CLDR contains some short number formats, for example in English

1,000 can become 1K, 12,100,000 can become 12.1M.

https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-numbers-modern/main/en/numbers.json#L61-L88

Similarly, other languages can use this with their own characters

eg. 32,500,000 = 3250万

https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-numbers-modern/main/ja/numbers.json#L51-L66

Is there a method in Babel that allows us to use these formats for decimal numbers?

----

It seems that the data is loaded under "compact_decimal_formats" although there are no utility functions for using them.

As per comment @ https://github.com/python-babel/babel/blob/v2.10.3/scripts/import_cldr.py#L768-L774

```py
>>>Locale('en', 'US')._data["compact_decimal_formats"]["short"]["one"]["1000"]
<NumberPattern '0K'>
```

**Comment by jun66j5** [comment]
If the given number is negative, the formatted text is not compact.

```pycon
>>> numbers.format_decimal(123456789, compact='short', locale='en_US')
'123M'
>>> numbers.format_decimal(123456789, compact='short', locale='ja')
'1億'
>>> numbers.format_decimal(-123456789, compact='short', locale='en_US')
'-123,456,789'
>>> numbers.format_decimal(-123456789, compact='short', locale='ja')
'-123,456,789'
```
