### ISSUE TITLE
Formatting GBP with french local gives weird result

### ISSUE THREAD

**Issue by martinth** [python-babel/babel#911]
## Overview Description

If you format British pounds with a french locale you get a weird "intermediate" result that is half currency symbol, half ISO code.

## Steps to Reproduce

```
from babel.numbers import format_currency
print(format_currency(3.99, currency='GBP', locale='fr_FR'))
```

## Actual Results

```3,99 £GB```

## Expected Results

That is somewhat debatable. I think the number formatting should always come from the locale (e.g. a decimal comma for french, and dots for thousands splitting). For the currency symbol I see multiple Options:

- `£3,99` (currency symbol placement like local for GBP) 
- `3,99 £` (currency symbol placement like local Euro placement)
- `3,99 GBP` (fallback to not using the symbol but the ISO currency)
-  `GBP 3,99` (same, but place ISO code always at the front)

## Reproducibility

Always

**Comment by akx** [comment]
This is not a bug in Babel – it's [how the CLDR specifies `fr_FR` should format `GBP`](https://unicode-org.github.io/cldr-staging/charts/latest/summary/fr.html#1cb981a57c93d7bf).
