### ISSUE TITLE
format_compact_decimal incorrectly works when the pattern has no 0 characters

### ISSUE THREAD

**Issue by jun66j5** [python-babel/babel#931]
## Overview Description

`format_compact_decimal` incorrectly works when the pattern has no 0 characters. Also, it doesn't handle `count="1"` rule.

## Steps to Reproduce

```pycon
>>> from babel import numbers
>>> numbers.format_compact_decimal(1000, format_type='long', locale='it')
'mille1'  # should be 'mille'
>>> numbers.format_compact_decimal(1234, format_type='long', locale='it')
'mille1'  # should be '1 mila'
>>> numbers.format_compact_decimal(1000, format_type='long', locale='fr')
'1 millier'  # should be 'mille'
>>> numbers.format_compact_decimal(1234, format_type='long', locale='fr')
'1 millier'  # correct
```

## Additional Information

* https://github.com/unicode-org/cldr/blob/release-41/common/main/it.xml#L5210
* https://github.com/unicode-org/cldr/blob/release-41/common/main/fr.xml#L7743
* [Explicit 0 and 1 rules](https://unicode.org/reports/tr35/tr35-numbers.html#Explicit_0_1_rules)

**Comment by DenverCoder1** [comment]
With the "mille1" issue, this seems like it is likely more of an issue with `NumberPattern.apply`, right?

```py
>>> numbers.format_decimal(1234, format="example")
'example1234'
```

It probably should not include the number if the format does not have a place for it?

**Comment by DenverCoder1** [comment]
> should be '1 mila'

Are we certain about 1000 returning different pluralization than 1234?

Previously we had said `format_compact_decimal(21098765, locale='mk', format_type='long')` would return `21 милион` instead of `21 милиони` because the plural rule for 21 is "one".

This would contradict that and require us to modify that test.
