### ISSUE TITLE
CLDR old version

### ISSUE THREAD

**Issue by yuvalek** [python-babel/babel#942]
## Overview Description

The CLDR version is not updated.
You are using version 41 of CLDR and it does not include that Croatia uses Euro starting in January 2023.
version 42 of CLDR does include this.

## Steps to Reproduce

1.get_territory_currencies('HR')
2.
3.

## Actual Results
HRK

## Expected Results
EUR

## Additional Information
Please update CLDR to version 42

**Comment by lcurran** [comment]
+1 on this, would be great if this could be addressed ASAP

**Comment by lcurran** [comment]
@akx thank you for the speedy action! Do you have any estimate on timeline for when the fix will be out?
