### ISSUE TITLE
Unicode CLDR 42 out

### ISSUE THREAD

**Issue by bouboulov** [python-babel/babel#965]
Hello, i just saw that in the same time Unicode CLDR 42 was out at : https://cldr.unicode.org/index/downloads/cldr-42

I just modified the « sources » in the `download_import_cldr.py` file and it worked fine.

Here's my mod lines 13-17: 

```
URL = 'http://unicode.org/Public/cldr/42/cldr-common-42.0.zip'
FILENAME = 'cldr-common-42.0.zip'
# Via https://unicode.org/Public/cldr/42/hashes/SHASUM512
FILESUM = '315448fe6a9ac2d5a6a7fd1a27b38c5db30fed053654a803d50e3a8d06aa08ad153e8e57089fa094c561f41a54f37eecda0701b47a1813879902be71945aa38a'
BLKSIZE = 131072
```

Don't know if it's the right place to put it here, so let me know.

**Comment by jun66j5** [comment]
See #951 and #942.
