### ISSUE TITLE
`Locale.parse()` no longer accepts None as the locale identifier

### ISSUE THREAD

**Issue by neuroid** [python-babel/babel#977]
## Overview Description

`Locale.parse()` no longer accepts None as the locale identifier, [contrary to the type annotation](https://github.com/python-babel/babel/blob/56071c90116e6b9ebbb62ac072bcf032fc6987cb/babel/core.py#L266).

## Steps to Reproduce

```python
>>> from babel import Locale
>>> Locale.parse(None) is None
```

## Actual Results

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/lib/python3.8/site-packages/babel/core.py", line 317, in parse
    raise TypeError(f"Unexpected value for identifier: {identifier!r}")
TypeError: Unexpected value for identifier: None
```

## Expected Results

```python
True
```

## Reproducibility

👍 

## Additional Information

Arguably, the previous behaviour was useful. However, if this breaking change is intentional, the type annotation should be adjusted accordingly.

**Comment by akx** [comment]
This change was intentional (but I forgot to distil it into the changelog).

Why would the behaviour be useful?
