### ISSUE TITLE
Missing documentation on how to set the project up locally

### ISSUE THREAD

**Issue by bfontaine** [python-babel/babel#985]
Hello,
After seeing @akx’s comment on https://github.com/python-babel/babel/issues/725#issuecomment-1435059954 I thought I would clone the project and see what I can do to fix the issue, but I haven’t found any documentation regarding the local setup.

I figured out you have to run `make test-env` and then activate the virtualenv or use `./test-env/bin/pybabel` but I’m not sure if I need to do something else. `make test` doesn’t work on Ubuntu 20.04.1 LTS because there’s no `python` executable: it’s either `python2` or `python3` (#984), and even then it fails if you didn’t activate the virtualenv before running `make test` because it can’t find `pytest`. I activated the virtualenv and ran `make test`; it found `pytest` but failed on a `ModuleNotFoundError: No module named 'freezegun'`. I’m not sure if that’s normal and/or what step did I miss.

**Comment by akx** [comment]
You'll have an easier time if you `pip install tox`, then run `make tox-test`. The tox configuration includes the dependencies required for testing.

**Comment by akx** [comment]
Closed via #986 👍
