### ISSUE TITLE
Formatting date with Canadian Locale no longer returns date in Canadian format

### ISSUE THREAD

**Issue by Ollymid** [python-babel/babel#987]
## Overview Description

I have found that when passing Canadian Locale to the babel format_date function (using the latest version v2.12.1) the date gets formatted to US date format (Month/Day/Year) rather than Canadian date format, which is the same as the international standard format (Year-Month-Day). 

We also use `en_US` and `en_UK` locales but they produced formatted dates as expected

## Steps to Reproduce

```
>>> from babel import Locale
>>> locale = Locale.parse('en_CA')
>>> locale
Locale('en', territory='CA')

>>> from datetime import datetime
>>> DATE_TUPLE = (2023, 11, 12, 0, 0, 0)
>>> d = datetime(*DATE_TUPLE)
>>> d
datetime.datetime(2023, 11, 12, 0, 0)

>>> from babel.dates import format_date
>>> d = timestamp
>>> format = 'short'
>>> day = format_date(d, locale=locale, format=format)
```

## Actual Results

Results with babel v2.12.1:
```
>>> day
'11/12/23'
```

## Expected Results

Results with babel v2.11.0:
```
>>> day
'2023-11-12'
```

**Comment by akx** [comment]
According to [the delta](https://unicode-org.github.io/cldr-staging/charts/latest/delta/en.html#Formats%20-%20Standard%20-%20Date%20Formats) this seems to have been a deliberate change in the CLDR data. 

You could bring this up over on the CLDR channels: https://github.com/unicode-org/cldr/blob/main/docs/requesting_changes.md

**Comment by Ollymid** [comment]
Thanks @akx  - Looks like someone else is already on to it 
https://github.com/unicode-org/cldr/pull/2759

**Comment by akx** [comment]
It will require a Babel version update, since the CLDR data is parsed and converted during the build process.

**Comment by srl295** [comment]
@akx Hi! beta version of CLDR coming soon. Do you pull from XML or JSON?

**Comment by akx** [comment]
@srl295 XML.
