### ISSUE TITLE
Any plan to load the latest version of CLDR? 

### ISSUE THREAD

**Issue by hanteng** [python-babel/babel#99]
Any plan to load the latest version of CLDR? I have tried to modified the code to load the CLDR 25, with only some limited success. Pluralization rules appear to need more work to digest the CLDR 25.

**Comment by benselme** [comment]
See #135 for preliminary cldr-24 support.

**Comment by srl295** [comment]
@benselme It's a good improvement,  CLDR 26 was released in August, 2014 for what it's worth. Please make use of resources such as the [cldr-users](http://www.unicode.org/consortium/distlist-cldr-users.html) list and the bug tracker on http://cldr.unicode.org/

**Comment by benselme** [comment]
My plan is to incrementally get to the latest version.

**Comment by srl295** [comment]
@benselme makes sense.

**Comment by sils1297** [comment]
Hi, closing this one as a duplicate of https://github.com/python-babel/babel/issues/226 . I'd love to see a PR solving that one, be it incrementally or not.
