### ISSUE TITLE
No Template Literals support  for .js files.

### ISSUE THREAD

**Issue by wolkodlack** [python-babel/babel#997]
## Overview Description

No Template Literals support  for .js files.

## Steps to Reproduce

1. Update babel.cfg
```
[javascript: **/static/**.js]
encoding = utf-8
extract_messages=_,gettext,ngettext
```
2. Create test.js with Template Literal e.g.
```
let hmtl = `<h3>${gettext("Some string to translate")}</h3>`;
```

3. Execute extractor
pybabel extract -F config/babel.cfg  -o messages.pot .

## Actual Results
No translate entries added to the messages.pot
## Expected Results
It would be good to find expected entries. 
```
msgid "Some string to translate"
msgstr ""
```

## Additional Information
Could be workarounded by adding same call outside of Template Literal
_("Some string to translate");

Is it possible to fix this case? Thank you.

**Comment by oomsveta** [comment]
Hello, I just ran into the same problem! I solved it by calling the `extract` function with the `parse_template_string` option set to `True`. I also had to update the version of the library as it doesn't seem to be supported until version 2.12.0.

**Comment by akx** [comment]
Yep – this was added pretty recently and needs opt-in; see above :)
